[
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/205109034",
    "html_url": "https://github.com/pandas-dev/pandas/issues/12723#issuecomment-205109034",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/12723",
    "id": 205109034,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIwNTEwOTAzNA==",
    "user": {
      "login": "facaiy",
      "id": 1112263,
      "node_id": "MDQ6VXNlcjExMTIyNjM=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1112263?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/facaiy",
      "html_url": "https://github.com/facaiy",
      "followers_url": "https://api.github.com/users/facaiy/followers",
      "following_url": "https://api.github.com/users/facaiy/following{/other_user}",
      "gists_url": "https://api.github.com/users/facaiy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/facaiy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/facaiy/subscriptions",
      "organizations_url": "https://api.github.com/users/facaiy/orgs",
      "repos_url": "https://api.github.com/users/facaiy/repos",
      "events_url": "https://api.github.com/users/facaiy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/facaiy/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-04T02:48:24Z",
    "updated_at": "2016-04-04T02:48:24Z",
    "author_association": "CONTRIBUTOR",
    "body": "I'd like to take a try.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/205114693",
    "html_url": "https://github.com/pandas-dev/pandas/issues/12723#issuecomment-205114693",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/12723",
    "id": 205114693,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIwNTExNDY5Mw==",
    "user": {
      "login": "facaiy",
      "id": 1112263,
      "node_id": "MDQ6VXNlcjExMTIyNjM=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1112263?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/facaiy",
      "html_url": "https://github.com/facaiy",
      "followers_url": "https://api.github.com/users/facaiy/followers",
      "following_url": "https://api.github.com/users/facaiy/following{/other_user}",
      "gists_url": "https://api.github.com/users/facaiy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/facaiy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/facaiy/subscriptions",
      "organizations_url": "https://api.github.com/users/facaiy/orgs",
      "repos_url": "https://api.github.com/users/facaiy/repos",
      "events_url": "https://api.github.com/users/facaiy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/facaiy/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-04T03:10:12Z",
    "updated_at": "2016-04-04T03:19:22Z",
    "author_association": "CONTRIBUTOR",
    "body": "It breaks [here](https://github.com/pydata/pandas/blob/602883a34a818f47f90651de99d786773b72d4a7/pandas/core/ops.py#L1089).\n\n`return self._combine_const(other, na_op)` miss `fill_value` parameter.\n\nSo, we can fix it before the method or in the method of DataFrame, \nwhich method is better? \n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/205146135",
    "html_url": "https://github.com/pandas-dev/pandas/issues/12723#issuecomment-205146135",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/12723",
    "id": 205146135,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIwNTE0NjEzNQ==",
    "user": {
      "login": "facaiy",
      "id": 1112263,
      "node_id": "MDQ6VXNlcjExMTIyNjM=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1112263?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/facaiy",
      "html_url": "https://github.com/facaiy",
      "followers_url": "https://api.github.com/users/facaiy/followers",
      "following_url": "https://api.github.com/users/facaiy/following{/other_user}",
      "gists_url": "https://api.github.com/users/facaiy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/facaiy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/facaiy/subscriptions",
      "organizations_url": "https://api.github.com/users/facaiy/orgs",
      "repos_url": "https://api.github.com/users/facaiy/repos",
      "events_url": "https://api.github.com/users/facaiy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/facaiy/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-04T05:49:35Z",
    "updated_at": "2016-04-04T05:49:35Z",
    "author_association": "CONTRIBUTOR",
    "body": "The fix is not complete, I find that the unexpected behavior exists also in Series.\n"
  }
]
