[
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/231609818",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-231609818",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 231609818,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzMTYwOTgxOA==",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-10T20:43:35Z",
    "updated_at": "2016-07-10T20:43:35Z",
    "author_association": "CONTRIBUTOR",
    "body": "in the future pls don't open new PR's for the same issue, just push to the old one. it causes extra work.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/231610674",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-231610674",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 231610674,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzMTYxMDY3NA==",
    "user": {
      "login": "codecov-io",
      "id": 8655789,
      "node_id": "MDQ6VXNlcjg2NTU3ODk=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/8655789?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/codecov-io",
      "html_url": "https://github.com/codecov-io",
      "followers_url": "https://api.github.com/users/codecov-io/followers",
      "following_url": "https://api.github.com/users/codecov-io/following{/other_user}",
      "gists_url": "https://api.github.com/users/codecov-io/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/codecov-io/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/codecov-io/subscriptions",
      "organizations_url": "https://api.github.com/users/codecov-io/orgs",
      "repos_url": "https://api.github.com/users/codecov-io/repos",
      "events_url": "https://api.github.com/users/codecov-io/events{/privacy}",
      "received_events_url": "https://api.github.com/users/codecov-io/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-10T21:02:07Z",
    "updated_at": "2016-08-17T15:38:27Z",
    "author_association": "NONE",
    "body": "## [Current coverage](https://codecov.io/gh/pydata/pandas/pull/13608?src=pr) is 85.25% (diff: 3.57%)\n\n> Merging [#13608](https://codecov.io/gh/pydata/pandas/pull/13608?src=pr) into [master](https://codecov.io/gh/pydata/pandas/branch/master?src=pr) will decrease coverage by **0.05%**\n\n``` diff\n@@             master     #13608   diff @@\n==========================================\n  Files           139        139          \n  Lines         50143      50272   +129   \n  Methods           0          0          \n  Messages          0          0          \n  Branches          0          0          \n==========================================\n+ Hits          42777      42857    +80   \n- Misses         7366       7415    +49   \n  Partials          0          0          \n```\n\n> Powered by [Codecov](https://codecov.io?src=pr). Last update [7e15923...a65b3f1](https://codecov.io/gh/pydata/pandas/compare/7e15923d908a42008fb7fecde58be626277fd82e...a65b3f170582343fcb7fdede77f1c4136702e161?src=pr)\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/231610683",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-231610683",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 231610683,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzMTYxMDY4Mw==",
    "user": {
      "login": "mhaseebtariq",
      "id": 7199752,
      "node_id": "MDQ6VXNlcjcxOTk3NTI=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7199752?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mhaseebtariq",
      "html_url": "https://github.com/mhaseebtariq",
      "followers_url": "https://api.github.com/users/mhaseebtariq/followers",
      "following_url": "https://api.github.com/users/mhaseebtariq/following{/other_user}",
      "gists_url": "https://api.github.com/users/mhaseebtariq/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mhaseebtariq/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mhaseebtariq/subscriptions",
      "organizations_url": "https://api.github.com/users/mhaseebtariq/orgs",
      "repos_url": "https://api.github.com/users/mhaseebtariq/repos",
      "events_url": "https://api.github.com/users/mhaseebtariq/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mhaseebtariq/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-10T21:02:18Z",
    "updated_at": "2016-07-10T21:02:18Z",
    "author_association": "CONTRIBUTOR",
    "body": "@jreback Got it. Apologies for that! This was my first contribution - the last PR got a bit messy. Will be careful next time. Thanks!\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/231610746",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-231610746",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 231610746,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzMTYxMDc0Ng==",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-10T21:03:22Z",
    "updated_at": "2016-07-10T21:03:22Z",
    "author_association": "CONTRIBUTOR",
    "body": "no prob. It just keeps a better chain to have a single PR.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/232276938",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-232276938",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 232276938,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzMjI3NjkzOA==",
    "user": {
      "login": "mhaseebtariq",
      "id": 7199752,
      "node_id": "MDQ6VXNlcjcxOTk3NTI=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7199752?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mhaseebtariq",
      "html_url": "https://github.com/mhaseebtariq",
      "followers_url": "https://api.github.com/users/mhaseebtariq/followers",
      "following_url": "https://api.github.com/users/mhaseebtariq/following{/other_user}",
      "gists_url": "https://api.github.com/users/mhaseebtariq/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mhaseebtariq/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mhaseebtariq/subscriptions",
      "organizations_url": "https://api.github.com/users/mhaseebtariq/orgs",
      "repos_url": "https://api.github.com/users/mhaseebtariq/repos",
      "events_url": "https://api.github.com/users/mhaseebtariq/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mhaseebtariq/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-13T07:24:45Z",
    "updated_at": "2016-07-13T07:24:45Z",
    "author_association": "CONTRIBUTOR",
    "body": "@jreback the new method that I added has some googleapiclient imports which cause the test to not completely capture the lines of codes. Can someone please have a look and close or suggest further actions.\n\nThanks,\nHaseeb\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/232321427",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-232321427",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 232321427,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzMjMyMTQyNw==",
    "user": {
      "login": "mhaseebtariq",
      "id": 7199752,
      "node_id": "MDQ6VXNlcjcxOTk3NTI=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7199752?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mhaseebtariq",
      "html_url": "https://github.com/mhaseebtariq",
      "followers_url": "https://api.github.com/users/mhaseebtariq/followers",
      "following_url": "https://api.github.com/users/mhaseebtariq/following{/other_user}",
      "gists_url": "https://api.github.com/users/mhaseebtariq/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mhaseebtariq/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mhaseebtariq/subscriptions",
      "organizations_url": "https://api.github.com/users/mhaseebtariq/orgs",
      "repos_url": "https://api.github.com/users/mhaseebtariq/repos",
      "events_url": "https://api.github.com/users/mhaseebtariq/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mhaseebtariq/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-13T10:48:41Z",
    "updated_at": "2016-07-13T10:48:41Z",
    "author_association": "CONTRIBUTOR",
    "body": "@jreback I will incorporate all the changes you suggested. Thank you for your time!\n\np.s. things like nested try/catch; staticmethod; etc. I implemented these to trick codecov and nosetests to cover/pass test for the new method. I will revert these changes.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/232601802",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-232601802",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 232601802,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzMjYwMTgwMg==",
    "user": {
      "login": "mhaseebtariq",
      "id": 7199752,
      "node_id": "MDQ6VXNlcjcxOTk3NTI=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7199752?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mhaseebtariq",
      "html_url": "https://github.com/mhaseebtariq",
      "followers_url": "https://api.github.com/users/mhaseebtariq/followers",
      "following_url": "https://api.github.com/users/mhaseebtariq/following{/other_user}",
      "gists_url": "https://api.github.com/users/mhaseebtariq/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mhaseebtariq/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mhaseebtariq/subscriptions",
      "organizations_url": "https://api.github.com/users/mhaseebtariq/orgs",
      "repos_url": "https://api.github.com/users/mhaseebtariq/repos",
      "events_url": "https://api.github.com/users/mhaseebtariq/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mhaseebtariq/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-14T08:34:21Z",
    "updated_at": "2016-07-14T08:34:21Z",
    "author_association": "CONTRIBUTOR",
    "body": "@jreback incorporated the suggested changes. Thanks! :)\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/237829492",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-237829492",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 237829492,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzNzgyOTQ5Mg==",
    "user": {
      "login": "mhaseebtariq",
      "id": 7199752,
      "node_id": "MDQ6VXNlcjcxOTk3NTI=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7199752?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mhaseebtariq",
      "html_url": "https://github.com/mhaseebtariq",
      "followers_url": "https://api.github.com/users/mhaseebtariq/followers",
      "following_url": "https://api.github.com/users/mhaseebtariq/following{/other_user}",
      "gists_url": "https://api.github.com/users/mhaseebtariq/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mhaseebtariq/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mhaseebtariq/subscriptions",
      "organizations_url": "https://api.github.com/users/mhaseebtariq/orgs",
      "repos_url": "https://api.github.com/users/mhaseebtariq/repos",
      "events_url": "https://api.github.com/users/mhaseebtariq/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mhaseebtariq/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-05T11:39:34Z",
    "updated_at": "2016-08-05T11:39:34Z",
    "author_association": "CONTRIBUTOR",
    "body": "Hi @jreback I was wondering - did you have a look at my last changes? Is the pull request eligible to be merged? Thanks! :)\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/237831383",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-237831383",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 237831383,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzNzgzMTM4Mw==",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-05T11:51:16Z",
    "updated_at": "2016-08-05T11:51:16Z",
    "author_association": "CONTRIBUTOR",
    "body": "needs tests\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/237834511",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-237834511",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 237834511,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzNzgzNDUxMQ==",
    "user": {
      "login": "mhaseebtariq",
      "id": 7199752,
      "node_id": "MDQ6VXNlcjcxOTk3NTI=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7199752?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mhaseebtariq",
      "html_url": "https://github.com/mhaseebtariq",
      "followers_url": "https://api.github.com/users/mhaseebtariq/followers",
      "following_url": "https://api.github.com/users/mhaseebtariq/following{/other_user}",
      "gists_url": "https://api.github.com/users/mhaseebtariq/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mhaseebtariq/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mhaseebtariq/subscriptions",
      "organizations_url": "https://api.github.com/users/mhaseebtariq/orgs",
      "repos_url": "https://api.github.com/users/mhaseebtariq/repos",
      "events_url": "https://api.github.com/users/mhaseebtariq/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mhaseebtariq/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-05T12:09:57Z",
    "updated_at": "2016-08-05T12:16:03Z",
    "author_association": "CONTRIBUTOR",
    "body": "@jreback I have written this test \"test_get_application_default_credentials_should_not_throw_error\" which should call (cover) the new method I've added. The \"test environment\" is probably skipping (TestGBQConnectorIntegration.setUp) this test because \"project_id\" is not set. I am guessing - even if I add more tests they will be skipped. As you can see from the coverage report - not even the first line of the method is covered - \nhttps://codecov.io/gh/pydata/pandas/compare/5701c69369264f3aa6f571384602ceec1133dabc...d4c7e3d33eca9d88a308802c8921addec40b77b9\n\nIf I am not understanding this correctly - could you please guide me how to solve this. Thank you for your time!\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/238677288",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-238677288",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 238677288,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzODY3NzI4OA==",
    "user": {
      "login": "mhaseebtariq",
      "id": 7199752,
      "node_id": "MDQ6VXNlcjcxOTk3NTI=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7199752?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mhaseebtariq",
      "html_url": "https://github.com/mhaseebtariq",
      "followers_url": "https://api.github.com/users/mhaseebtariq/followers",
      "following_url": "https://api.github.com/users/mhaseebtariq/following{/other_user}",
      "gists_url": "https://api.github.com/users/mhaseebtariq/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mhaseebtariq/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mhaseebtariq/subscriptions",
      "organizations_url": "https://api.github.com/users/mhaseebtariq/orgs",
      "repos_url": "https://api.github.com/users/mhaseebtariq/repos",
      "events_url": "https://api.github.com/users/mhaseebtariq/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mhaseebtariq/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-09T20:17:20Z",
    "updated_at": "2016-08-09T20:17:20Z",
    "author_association": "CONTRIBUTOR",
    "body": "Hi @jreback, do you think the pull request is fine now. The second test (test_get_application_default_credentials_returns_credentials) will only be executed (not skipped) if a google account is authenticated (for gcloud) on the environment.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/239027227",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-239027227",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 239027227,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzOTAyNzIyNw==",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-10T22:42:53Z",
    "updated_at": "2016-08-10T22:42:53Z",
    "author_association": "CONTRIBUTOR",
    "body": "cc @parthea can you give this a run.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/239677887",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-239677887",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 239677887,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzOTY3Nzg4Nw==",
    "user": {
      "login": "parthea",
      "id": 5184014,
      "node_id": "MDQ6VXNlcjUxODQwMTQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/5184014?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/parthea",
      "html_url": "https://github.com/parthea",
      "followers_url": "https://api.github.com/users/parthea/followers",
      "following_url": "https://api.github.com/users/parthea/following{/other_user}",
      "gists_url": "https://api.github.com/users/parthea/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/parthea/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/parthea/subscriptions",
      "organizations_url": "https://api.github.com/users/parthea/orgs",
      "repos_url": "https://api.github.com/users/parthea/repos",
      "events_url": "https://api.github.com/users/parthea/events{/privacy}",
      "received_events_url": "https://api.github.com/users/parthea/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-14T14:56:25Z",
    "updated_at": "2016-08-14T14:57:40Z",
    "author_association": "CONTRIBUTOR",
    "body": "Output from local run using oauth2client==1.2.\n\n37 tests skipped. Need to move `from oauth2client.client import GoogleCredentials` inside of try except since `oauth2client==1.2` doesn't have `client.GoogleCredentials`\n\n```\ntony@tonypc:~/pandas-master/pandas/io/tests$ nosetests test_gbq.py -vtest_import_google_api_python_client (pandas.io.tests.test_gbq.GBQUnitTests) ... SKIP: Could not import Google API Client.\ntest_read_gbq_with_corrupted_private_key_json_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... SKIP: Could not import Google API Client.\ntest_read_gbq_with_empty_private_key_file_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... SKIP: Could not import Google API Client.\ntest_read_gbq_with_empty_private_key_json_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... SKIP: Could not import Google API Client.\ntest_read_gbq_with_invalid_private_key_json_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... SKIP: Could not import Google API Client.\ntest_read_gbq_with_no_project_id_given_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... SKIP: Could not import Google API Client.\ntest_read_gbq_with_private_key_json_wrong_types_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... SKIP: Could not import Google API Client.\ntest_should_return_bigquery_booleans_as_python_booleans (pandas.io.tests.test_gbq.GBQUnitTests) ... SKIP: Could not import Google API Client.\ntest_should_return_bigquery_floats_as_python_floats (pandas.io.tests.test_gbq.GBQUnitTests) ... SKIP: Could not import Google API Client.\ntest_should_return_bigquery_integers_as_python_floats (pandas.io.tests.test_gbq.GBQUnitTests) ... SKIP: Could not import Google API Client.\ntest_should_return_bigquery_strings_as_python_strings (pandas.io.tests.test_gbq.GBQUnitTests) ... SKIP: Could not import Google API Client.\ntest_should_return_bigquery_timestamps_as_numpy_datetime (pandas.io.tests.test_gbq.GBQUnitTests) ... SKIP: Could not import Google API Client.\ntest_that_parse_data_works_properly (pandas.io.tests.test_gbq.GBQUnitTests) ... SKIP: Could not import Google API Client.\ntest_to_gbq_should_fail_if_invalid_table_name_passed (pandas.io.tests.test_gbq.GBQUnitTests) ... SKIP: Could not import Google API Client.\ntest_to_gbq_with_no_project_id_given_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... SKIP: Could not import Google API Client.\ntest_get_application_default_credentials_does_not_throw_error (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... SKIP: Could not import Google API Client.\ntest_get_application_default_credentials_returns_credentials (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... SKIP: Could not import Google API Client.\ntest_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... SKIP: Could not import Google API Client.\ntest_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... SKIP: Could not import Google API Client.\ntest_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... SKIP: Could not import Google API Client.\ntest_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... SKIP: Could not import Google API Client.\ntest_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... SKIP: Could not import Google API Client.\ntest_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... SKIP: Could not import Google API Client.\ntest_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... SKIP: Could not import Google API Client.\ntest_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... SKIP: Could not import Google API Client.\ntest_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... SKIP: Could not import Google API Client.\ntest_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... SKIP: Could not import Google API Client.\ntest_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... SKIP: Could not import Google API Client.\ntest_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... SKIP: Could not import Google API Client.\ntest_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... SKIP: Could not import Google API Client.\ntest_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... SKIP: Could not import Google API Client.\ntest_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... SKIP: Could not import Google API Client.\nSKIP: Could not import Google API Client.\nSKIP: Could not import Google API Client.\nSKIP: Could not import Google API Client.\nSKIP: Could not import Google API Client.\npandas.io.tests.test_gbq.test_requirements ... SKIP: Could not import Google API Client.\npandas.io.tests.test_gbq.test_generate_bq_schema_deprecated ... ok\n\n----------------------------------------------------------------------\nRan 34 tests in 0.789s\n\nOK (SKIP=37)\n```\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/239679209",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-239679209",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 239679209,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzOTY3OTIwOQ==",
    "user": {
      "login": "parthea",
      "id": 5184014,
      "node_id": "MDQ6VXNlcjUxODQwMTQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/5184014?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/parthea",
      "html_url": "https://github.com/parthea",
      "followers_url": "https://api.github.com/users/parthea/followers",
      "following_url": "https://api.github.com/users/parthea/following{/other_user}",
      "gists_url": "https://api.github.com/users/parthea/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/parthea/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/parthea/subscriptions",
      "organizations_url": "https://api.github.com/users/parthea/orgs",
      "repos_url": "https://api.github.com/users/parthea/repos",
      "events_url": "https://api.github.com/users/parthea/events{/privacy}",
      "received_events_url": "https://api.github.com/users/parthea/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-14T15:20:12Z",
    "updated_at": "2016-08-14T15:20:12Z",
    "author_association": "CONTRIBUTOR",
    "body": "@mhaseebtariq :+1: Lightning fast!\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/239681110",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-239681110",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 239681110,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzOTY4MTExMA==",
    "user": {
      "login": "parthea",
      "id": 5184014,
      "node_id": "MDQ6VXNlcjUxODQwMTQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/5184014?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/parthea",
      "html_url": "https://github.com/parthea",
      "followers_url": "https://api.github.com/users/parthea/followers",
      "following_url": "https://api.github.com/users/parthea/following{/other_user}",
      "gists_url": "https://api.github.com/users/parthea/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/parthea/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/parthea/subscriptions",
      "organizations_url": "https://api.github.com/users/parthea/orgs",
      "repos_url": "https://api.github.com/users/parthea/repos",
      "events_url": "https://api.github.com/users/parthea/events{/privacy}",
      "received_events_url": "https://api.github.com/users/parthea/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-14T15:57:56Z",
    "updated_at": "2016-08-14T15:59:49Z",
    "author_association": "CONTRIBUTOR",
    "body": "All tests pass locally.\n\nI also found that Pandas GBQ integration now works seamlessly in [Google Datalab](https://cloud.google.com/datalab/docs/quickstarts/quickstart-local) with this PR.\n\nNote: This only works if user is already logged into Google Datalab. One observation that I noticed is that Google Datalab usually prompts the user to sign in if `oauth2client.client.GoogleCredentials.get_application_default()` fails, but in this case the exception is hidden in pandas, so user may not know that they need to sign in to Datalab in order to avoid the additional sign in process for pandas.\n\n```\ntony@tonypc:~/pandas-master/pandas/io/tests$ nosetests test_gbq.py -v\ntest_import_google_api_python_client (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_corrupted_private_key_json_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_empty_private_key_file_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_empty_private_key_json_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_invalid_private_key_json_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_no_project_id_given_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_private_key_json_wrong_types_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_booleans_as_python_booleans (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_floats_as_python_floats (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_integers_as_python_floats (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_strings_as_python_strings (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_timestamps_as_numpy_datetime (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_that_parse_data_works_properly (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_to_gbq_should_fail_if_invalid_table_name_passed (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_to_gbq_with_no_project_id_given_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_get_application_default_credentials_does_not_throw_error (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_get_application_default_credentials_returns_credentials (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... SKIP: Cannot get default_credentials from the environment!\ntest_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_bad_project_id (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_bad_table_name (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_column_order (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_column_order_plus_index (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_download_dataset_larger_than_200k_rows (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_index_column (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_invalid_option_for_sql_dialect (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_legacy_sql (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_malformed_query (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_arbitrary_timestamp (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_empty_strings (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_false_boolean (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_boolean (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_floats (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_integers (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_strings (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_timestamp (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_timestamp_unix_epoch (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_true_boolean (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_valid_floats (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_valid_integers (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_valid_strings (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_read_as_service_account_with_key_contents (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_read_as_service_account_with_key_path (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_standard_sql (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_unicode_string_conversion_and_normalization (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_zero_rows (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_create_dataset (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_create_table (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_dataset_does_not_exist (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_dataset_exists (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_delete_dataset (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_delete_table (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_generate_schema (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_google_upload_errors_should_raise_exception (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_list_dataset (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_list_table (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_list_table_zero_results (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_table_does_not_exist (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data_if_table_exists_append (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data_if_table_exists_fail (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data_if_table_exists_replace (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data_as_service_account_with_key_contents (pandas.io.tests.test_gbq.TestToGBQIntegrationServiceAccountKeyContents) ... ok\ntest_upload_data_as_service_account_with_key_path (pandas.io.tests.test_gbq.TestToGBQIntegrationServiceAccountKeyPath) ... ok\npandas.io.tests.test_gbq.test_requirements ... ok\npandas.io.tests.test_gbq.test_generate_bq_schema_deprecated ... ok\n\n----------------------------------------------------------------------\nRan 79 tests in 384.230s\n\nOK (SKIP=1)\n```\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/239691877",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-239691877",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 239691877,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzOTY5MTg3Nw==",
    "user": {
      "login": "parthea",
      "id": 5184014,
      "node_id": "MDQ6VXNlcjUxODQwMTQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/5184014?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/parthea",
      "html_url": "https://github.com/parthea",
      "followers_url": "https://api.github.com/users/parthea/followers",
      "following_url": "https://api.github.com/users/parthea/following{/other_user}",
      "gists_url": "https://api.github.com/users/parthea/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/parthea/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/parthea/subscriptions",
      "organizations_url": "https://api.github.com/users/parthea/orgs",
      "repos_url": "https://api.github.com/users/parthea/repos",
      "events_url": "https://api.github.com/users/parthea/events{/privacy}",
      "received_events_url": "https://api.github.com/users/parthea/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-14T19:30:02Z",
    "updated_at": "2016-08-14T19:38:11Z",
    "author_association": "CONTRIBUTOR",
    "body": "I receive the following error with `google-api-python-client==1.2` and `oauth2client>1.2`\n\n```\ntony@tonypc:~/pandas-master/pandas/io/tests$ nosetests test_gbq.py -v\ntest_import_google_api_python_client (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_corrupted_private_key_json_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_empty_private_key_file_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_empty_private_key_json_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_invalid_private_key_json_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_no_project_id_given_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_private_key_json_wrong_types_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_booleans_as_python_booleans (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_floats_as_python_floats (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_integers_as_python_floats (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_strings_as_python_strings (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_timestamps_as_numpy_datetime (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_that_parse_data_works_properly (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_to_gbq_should_fail_if_invalid_table_name_passed (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_to_gbq_with_no_project_id_given_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_get_application_default_credentials_does_not_throw_error (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ERROR\ntest_get_application_default_credentials_returns_credentials (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ERROR\ntest_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ERROR\ntest_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ERROR\ntest_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ERROR\ntest_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ERROR\ntest_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ERROR\ntest_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_bad_project_id (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_bad_table_name (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_column_order (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_column_order_plus_index (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_download_dataset_larger_than_200k_rows (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_index_column (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_invalid_option_for_sql_dialect (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_legacy_sql (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_malformed_query (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_should_properly_handle_arbitrary_timestamp (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_should_properly_handle_empty_strings (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_should_properly_handle_false_boolean (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_should_properly_handle_null_boolean (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_should_properly_handle_null_floats (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_should_properly_handle_null_integers (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_should_properly_handle_null_strings (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_should_properly_handle_null_timestamp (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_should_properly_handle_timestamp_unix_epoch (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_should_properly_handle_true_boolean (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_should_properly_handle_valid_floats (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_should_properly_handle_valid_integers (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_should_properly_handle_valid_strings (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_should_read_as_service_account_with_key_contents (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_read_as_service_account_with_key_path (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_standard_sql (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_unicode_string_conversion_and_normalization (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\ntest_zero_rows (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ERROR\nERROR\ntest_upload_data_as_service_account_with_key_contents (pandas.io.tests.test_gbq.TestToGBQIntegrationServiceAccountKeyContents) ... ok\ntest_upload_data_as_service_account_with_key_path (pandas.io.tests.test_gbq.TestToGBQIntegrationServiceAccountKeyPath) ... ok\npandas.io.tests.test_gbq.test_requirements ... ok\npandas.io.tests.test_gbq.test_generate_bq_schema_deprecated ... ok\n\n======================================================================\nERROR: test_get_application_default_credentials_does_not_throw_error (pandas.io.tests.test_gbq.TestGBQConnectorIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 220, in setUp\n    self.sut = gbq.GbqConnector(PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_get_application_default_credentials_returns_credentials (pandas.io.tests.test_gbq.TestGBQConnectorIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 220, in setUp\n    self.sut = gbq.GbqConnector(PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 220, in setUp\n    self.sut = gbq.GbqConnector(PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 220, in setUp\n    self.sut = gbq.GbqConnector(PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 220, in setUp\n    self.sut = gbq.GbqConnector(PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 220, in setUp\n    self.sut = gbq.GbqConnector(PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 220, in setUp\n    self.sut = gbq.GbqConnector(PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_bad_project_id (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 569, in test_bad_project_id\n    gbq.read_gbq(\"SELECT 1\", project_id='001')\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_bad_table_name (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 574, in test_bad_table_name\n    project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_column_order (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 546, in test_column_order\n    query, project_id=PROJECT_ID, col_order=col_order)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_column_order_plus_index (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 555, in test_column_order_plus_index\n    index_col='STRING_1', col_order=col_order)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_download_dataset_larger_than_200k_rows (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 583, in test_download_dataset_larger_than_200k_rows\n    project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_index_column (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 537, in test_index_column\n    query, project_id=PROJECT_ID, index_col=\"STRING_1\")\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_invalid_option_for_sql_dialect (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 639, in test_invalid_option_for_sql_dialect\n    dialect='standard')\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_legacy_sql (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 604, in test_legacy_sql\n    dialect='standard')\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_malformed_query (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 565, in test_malformed_query\n    project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_should_properly_handle_arbitrary_timestamp (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 494, in test_should_properly_handle_arbitrary_timestamp\n    df = gbq.read_gbq(query, project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_should_properly_handle_empty_strings (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 457, in test_should_properly_handle_empty_strings\n    df = gbq.read_gbq(query, project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_should_properly_handle_false_boolean (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 511, in test_should_properly_handle_false_boolean\n    df = gbq.read_gbq(query, project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_should_properly_handle_null_boolean (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 516, in test_should_properly_handle_null_boolean\n    df = gbq.read_gbq(query, project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_should_properly_handle_null_floats (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 483, in test_should_properly_handle_null_floats\n    df = gbq.read_gbq(query, project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_should_properly_handle_null_integers (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 472, in test_should_properly_handle_null_integers\n    df = gbq.read_gbq(query, project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_should_properly_handle_null_strings (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 462, in test_should_properly_handle_null_strings\n    df = gbq.read_gbq(query, project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_should_properly_handle_null_timestamp (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 501, in test_should_properly_handle_null_timestamp\n    df = gbq.read_gbq(query, project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_should_properly_handle_timestamp_unix_epoch (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 488, in test_should_properly_handle_timestamp_unix_epoch\n    df = gbq.read_gbq(query, project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_should_properly_handle_true_boolean (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 506, in test_should_properly_handle_true_boolean\n    df = gbq.read_gbq(query, project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_should_properly_handle_valid_floats (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 477, in test_should_properly_handle_valid_floats\n    df = gbq.read_gbq(query, project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_should_properly_handle_valid_integers (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 467, in test_should_properly_handle_valid_integers\n    df = gbq.read_gbq(query, project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_should_properly_handle_valid_strings (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 452, in test_should_properly_handle_valid_strings\n    df = gbq.read_gbq(query, project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_standard_sql (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 619, in test_standard_sql\n    gbq.read_gbq(standard_sql, project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_unicode_string_conversion_and_normalization (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 531, in test_unicode_string_conversion_and_normalization\n    df = gbq.read_gbq(query, project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test_zero_rows (pandas.io.tests.test_gbq.TestReadGBQIntegration)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 591, in test_zero_rows\n    project_id=PROJECT_ID)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 689, in read_gbq\n    dialect=dialect)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n======================================================================\nERROR: test suite for <class 'pandas.io.tests.test_gbq.TestToGBQIntegration'>\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/nose/suite.py\", line 209, in run\n    self.setUp()\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/nose/suite.py\", line 292, in setUp\n    self.setupContext(ancestor)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/nose/suite.py\", line 315, in setupContext\n    try_run(context, names)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/nose/util.py\", line 471, in try_run\n    return func()\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 658, in setUpClass\n    clean_gbq_environment()\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 177, in clean_gbq_environment\n    dataset = gbq._Dataset(PROJECT_ID, private_key=private_key)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 972, in __init__\n    private_key)\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 156, in __init__\n    self.credentials = self.get_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 164, in get_credentials\n    credentials = self.get_application_default_credentials()\n  File \"/home/tony/pandas-master/pandas/io/gbq.py\", line 206, in get_application_default_credentials\n    bigquery_service = build('bigquery', 'v2', credentials=credentials)\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n----------------------------------------------------------------------\nRan 63 tests in 94.503s\n\nFAILED (errors=33)\n```\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/239691918",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-239691918",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 239691918,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzOTY5MTkxOA==",
    "user": {
      "login": "parthea",
      "id": 5184014,
      "node_id": "MDQ6VXNlcjUxODQwMTQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/5184014?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/parthea",
      "html_url": "https://github.com/parthea",
      "followers_url": "https://api.github.com/users/parthea/followers",
      "following_url": "https://api.github.com/users/parthea/following{/other_user}",
      "gists_url": "https://api.github.com/users/parthea/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/parthea/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/parthea/subscriptions",
      "organizations_url": "https://api.github.com/users/parthea/orgs",
      "repos_url": "https://api.github.com/users/parthea/repos",
      "events_url": "https://api.github.com/users/parthea/events{/privacy}",
      "received_events_url": "https://api.github.com/users/parthea/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-14T19:30:35Z",
    "updated_at": "2016-08-14T19:30:35Z",
    "author_association": "CONTRIBUTOR",
    "body": "Additional output from local test\n\n```\n>>> import googleapiclient\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\nImportError: No module named googleapiclient\n>>> import apiclient\n>>> apiclient.__version__\n'1.2'\n>>> from oauth2client.client import GoogleCredentials\n>>> credentials = GoogleCredentials.get_application_default()\n>>> from googleapiclient.discovery import build\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\nImportError: No module named googleapiclient.discovery\n>>> from apiclient.discovery import build\n>>> bigquery_service = build('bigquery', 'v2', credentials=credentials)\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/home/tony/anaconda/lib/python2.7/site-packages/oauth2client/util.py\", line 142, in positional_wrapper\n    return wrapped(*args, **kwargs)\nTypeError: build() got an unexpected keyword argument 'credentials'\n\n```\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/239713939",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-239713939",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 239713939,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzOTcxMzkzOQ==",
    "user": {
      "login": "parthea",
      "id": 5184014,
      "node_id": "MDQ6VXNlcjUxODQwMTQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/5184014?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/parthea",
      "html_url": "https://github.com/parthea",
      "followers_url": "https://api.github.com/users/parthea/followers",
      "following_url": "https://api.github.com/users/parthea/following{/other_user}",
      "gists_url": "https://api.github.com/users/parthea/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/parthea/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/parthea/subscriptions",
      "organizations_url": "https://api.github.com/users/parthea/orgs",
      "repos_url": "https://api.github.com/users/parthea/repos",
      "events_url": "https://api.github.com/users/parthea/events{/privacy}",
      "received_events_url": "https://api.github.com/users/parthea/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-15T01:45:32Z",
    "updated_at": "2016-08-15T01:45:32Z",
    "author_association": "CONTRIBUTOR",
    "body": "Looks good to me. I tested 3 different configurations. \n\nTest scenario 1: \noauth2client==1.2\ngoogle-api-python-client==1.2\n\n```\n>>> import oauth2client\n>>> oauth2client.__version__\n'1.2'\n>>> import apiclient\n>>> apiclient.__version__\n'1.2'\n>>> quit()\ntony@tonypc:~/pandas-master/pandas/io/tests$ nosetests test_gbq.py -v\ntest_import_google_api_python_client (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_corrupted_private_key_json_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_empty_private_key_file_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_empty_private_key_json_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_invalid_private_key_json_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_no_project_id_given_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_private_key_json_wrong_types_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_booleans_as_python_booleans (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_floats_as_python_floats (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_integers_as_python_floats (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_strings_as_python_strings (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_timestamps_as_numpy_datetime (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_that_parse_data_works_properly (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_to_gbq_should_fail_if_invalid_table_name_passed (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_to_gbq_with_no_project_id_given_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_get_application_default_credentials_does_not_throw_error (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_get_application_default_credentials_returns_credentials (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... SKIP: Cannot get default_credentials from the environment!\ntest_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_bad_project_id (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_bad_table_name (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_column_order (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_column_order_plus_index (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_download_dataset_larger_than_200k_rows (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_index_column (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_invalid_option_for_sql_dialect (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_legacy_sql (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_malformed_query (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_arbitrary_timestamp (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_empty_strings (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_false_boolean (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_boolean (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_floats (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_integers (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_strings (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_timestamp (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_timestamp_unix_epoch (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_true_boolean (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_valid_floats (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_valid_integers (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_valid_strings (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_read_as_service_account_with_key_contents (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_read_as_service_account_with_key_path (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_standard_sql (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_unicode_string_conversion_and_normalization (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_zero_rows (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_create_dataset (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_create_table (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_dataset_does_not_exist (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_dataset_exists (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_delete_dataset (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_delete_table (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_generate_schema (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_google_upload_errors_should_raise_exception (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_list_dataset (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_list_table (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_list_table_zero_results (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_table_does_not_exist (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data_if_table_exists_append (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data_if_table_exists_fail (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data_if_table_exists_replace (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data_as_service_account_with_key_contents (pandas.io.tests.test_gbq.TestToGBQIntegrationServiceAccountKeyContents) ... ok\ntest_upload_data_as_service_account_with_key_path (pandas.io.tests.test_gbq.TestToGBQIntegrationServiceAccountKeyPath) ... ok\npandas.io.tests.test_gbq.test_requirements ... ok\npandas.io.tests.test_gbq.test_generate_bq_schema_deprecated ... ok\n\n----------------------------------------------------------------------\nRan 79 tests in 404.635s\n\nOK (SKIP=1)\n```\n\nTest scenario 2: \noauth2client==3.0.0\ngoogle-api-python-client==1.2\n\n```\n>>> import oauth2client\n>>> oauth2client.__version__\n'3.0.0'\n>>> import apiclient\n>>> apiclient.__version__\n'1.2'\n>>> quit()\ntony@tonypc:~/pandas-master/pandas/io/tests$ nosetests test_gbq.py -v\ntest_import_google_api_python_client (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_corrupted_private_key_json_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_empty_private_key_file_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_empty_private_key_json_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_invalid_private_key_json_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_no_project_id_given_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_private_key_json_wrong_types_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_booleans_as_python_booleans (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_floats_as_python_floats (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_integers_as_python_floats (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_strings_as_python_strings (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_timestamps_as_numpy_datetime (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_that_parse_data_works_properly (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_to_gbq_should_fail_if_invalid_table_name_passed (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_to_gbq_with_no_project_id_given_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_get_application_default_credentials_does_not_throw_error (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_get_application_default_credentials_returns_credentials (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... SKIP: Cannot get default_credentials from the environment!\ntest_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_bad_project_id (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_bad_table_name (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_column_order (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_column_order_plus_index (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_download_dataset_larger_than_200k_rows (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_index_column (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_invalid_option_for_sql_dialect (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_legacy_sql (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_malformed_query (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_arbitrary_timestamp (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_empty_strings (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_false_boolean (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_boolean (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_floats (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_integers (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_strings (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_timestamp (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_timestamp_unix_epoch (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_true_boolean (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_valid_floats (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_valid_integers (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_valid_strings (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_read_as_service_account_with_key_contents (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_read_as_service_account_with_key_path (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_standard_sql (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_unicode_string_conversion_and_normalization (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_zero_rows (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_create_dataset (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_create_table (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_dataset_does_not_exist (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_dataset_exists (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_delete_dataset (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_delete_table (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_generate_schema (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_google_upload_errors_should_raise_exception (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_list_dataset (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_list_table (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_list_table_zero_results (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_table_does_not_exist (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data_if_table_exists_append (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data_if_table_exists_fail (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data_if_table_exists_replace (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data_as_service_account_with_key_contents (pandas.io.tests.test_gbq.TestToGBQIntegrationServiceAccountKeyContents) ... ok\ntest_upload_data_as_service_account_with_key_path (pandas.io.tests.test_gbq.TestToGBQIntegrationServiceAccountKeyPath) ... ok\npandas.io.tests.test_gbq.test_requirements ... ok\npandas.io.tests.test_gbq.test_generate_bq_schema_deprecated ... ok\n\n----------------------------------------------------------------------\nRan 79 tests in 414.826s\n\nOK (SKIP=1)\n```\n\nTest scenario 3: \noauth2client==3.0.0\ngoogle-api-python-client==1.5.1\nNote: expect `test_import_google_api_python_client()` to fail. This is by design to ensure that we test `google-api-python-client==1.2`\n\n```\n>>> import oauth2client\n>>> oauth2client.__version__\n'3.0.0'\n>>> import googleapiclient\n>>> googleapiclient.__version__\n'1.5.1'\n>>> quit()\ntony@tonypc:~/pandas-master/pandas/io/tests$ nosetests test_gbq.py -v\ntest_import_google_api_python_client (pandas.io.tests.test_gbq.GBQUnitTests) ... FAIL\ntest_read_gbq_with_corrupted_private_key_json_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_empty_private_key_file_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_empty_private_key_json_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_invalid_private_key_json_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_no_project_id_given_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_read_gbq_with_private_key_json_wrong_types_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_booleans_as_python_booleans (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_floats_as_python_floats (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_integers_as_python_floats (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_strings_as_python_strings (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_should_return_bigquery_timestamps_as_numpy_datetime (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_that_parse_data_works_properly (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_to_gbq_should_fail_if_invalid_table_name_passed (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_to_gbq_with_no_project_id_given_should_fail (pandas.io.tests.test_gbq.GBQUnitTests) ... ok\ntest_get_application_default_credentials_does_not_throw_error (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_get_application_default_credentials_returns_credentials (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... SKIP: Cannot get default_credentials from the environment!\ntest_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorIntegration) ... ok\ntest_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyContentsIntegration) ... ok\ntest_should_be_able_to_get_a_bigquery_service (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_get_results_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_get_schema_from_query (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_get_valid_credentials (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_should_be_able_to_make_a_connector (pandas.io.tests.test_gbq.TestGBQConnectorServiceAccountKeyPathIntegration) ... ok\ntest_bad_project_id (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_bad_table_name (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_column_order (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_column_order_plus_index (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_download_dataset_larger_than_200k_rows (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_index_column (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_invalid_option_for_sql_dialect (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_legacy_sql (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_malformed_query (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_arbitrary_timestamp (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_empty_strings (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_false_boolean (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_boolean (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_floats (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_integers (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_strings (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_null_timestamp (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_timestamp_unix_epoch (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_true_boolean (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_valid_floats (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_valid_integers (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_properly_handle_valid_strings (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_read_as_service_account_with_key_contents (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_should_read_as_service_account_with_key_path (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_standard_sql (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_unicode_string_conversion_and_normalization (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_zero_rows (pandas.io.tests.test_gbq.TestReadGBQIntegration) ... ok\ntest_create_dataset (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_create_table (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_dataset_does_not_exist (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_dataset_exists (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_delete_dataset (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_delete_table (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_generate_schema (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_google_upload_errors_should_raise_exception (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_list_dataset (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_list_table (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_list_table_zero_results (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_table_does_not_exist (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data_if_table_exists_append (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data_if_table_exists_fail (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data_if_table_exists_replace (pandas.io.tests.test_gbq.TestToGBQIntegration) ... ok\ntest_upload_data_as_service_account_with_key_contents (pandas.io.tests.test_gbq.TestToGBQIntegrationServiceAccountKeyContents) ... ok\ntest_upload_data_as_service_account_with_key_path (pandas.io.tests.test_gbq.TestToGBQIntegrationServiceAccountKeyPath) ... ok\npandas.io.tests.test_gbq.test_requirements ... ok\npandas.io.tests.test_gbq.test_generate_bq_schema_deprecated ... ok\n\n======================================================================\nFAIL: test_import_google_api_python_client (pandas.io.tests.test_gbq.GBQUnitTests)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/tony/pandas-master/pandas/io/tests/test_gbq.py\", line 332, in test_import_google_api_python_client\n    from googleapiclient.errors import HttpError  # noqa\n  File \"/home/tony/pandas-master/pandas/util/testing.py\", line 2435, in __exit__\n    raise AssertionError(\"{0} not raised.\".format(name))\nAssertionError: ImportError not raised.\n\n----------------------------------------------------------------------\nRan 79 tests in 398.691s\n\nFAILED (SKIP=1, failures=1)\n```\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/240332611",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-240332611",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 240332611,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI0MDMzMjYxMQ==",
    "user": {
      "login": "mhaseebtariq",
      "id": 7199752,
      "node_id": "MDQ6VXNlcjcxOTk3NTI=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7199752?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mhaseebtariq",
      "html_url": "https://github.com/mhaseebtariq",
      "followers_url": "https://api.github.com/users/mhaseebtariq/followers",
      "following_url": "https://api.github.com/users/mhaseebtariq/following{/other_user}",
      "gists_url": "https://api.github.com/users/mhaseebtariq/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mhaseebtariq/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mhaseebtariq/subscriptions",
      "organizations_url": "https://api.github.com/users/mhaseebtariq/orgs",
      "repos_url": "https://api.github.com/users/mhaseebtariq/repos",
      "events_url": "https://api.github.com/users/mhaseebtariq/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mhaseebtariq/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-17T07:16:56Z",
    "updated_at": "2016-08-17T07:16:56Z",
    "author_association": "CONTRIBUTOR",
    "body": "Hi @jreback I was wondering when will this pull request be closed - all tests have passed now. Thanks!\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/240375646",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-240375646",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 240375646,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI0MDM3NTY0Ng==",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-17T10:38:01Z",
    "updated_at": "2016-08-17T10:38:01Z",
    "author_association": "CONTRIBUTOR",
    "body": "This is not even running thru travis at all. pls add the deps that are required to one of the `ci\\*` files that currently do the bigquery import tests.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/240381510",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-240381510",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 240381510,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI0MDM4MTUxMA==",
    "user": {
      "login": "mhaseebtariq",
      "id": 7199752,
      "node_id": "MDQ6VXNlcjcxOTk3NTI=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7199752?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mhaseebtariq",
      "html_url": "https://github.com/mhaseebtariq",
      "followers_url": "https://api.github.com/users/mhaseebtariq/followers",
      "following_url": "https://api.github.com/users/mhaseebtariq/following{/other_user}",
      "gists_url": "https://api.github.com/users/mhaseebtariq/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mhaseebtariq/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mhaseebtariq/subscriptions",
      "organizations_url": "https://api.github.com/users/mhaseebtariq/orgs",
      "repos_url": "https://api.github.com/users/mhaseebtariq/repos",
      "events_url": "https://api.github.com/users/mhaseebtariq/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mhaseebtariq/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-17T11:10:04Z",
    "updated_at": "2016-08-17T11:16:40Z",
    "author_association": "CONTRIBUTOR",
    "body": "@jreback on: \"...add deps that are required to one of the `ci\\*` files...\"\n\nThe dependent library is already mentioned in `requirements-2.7.pip` and `requirements-3.4.pip` -\n\n`google-api-python-client==1.2` (wrong version)\n\nThis change requires google-api-python-client==**1.5** though.\n\nWhat do you suggest I should do then - change the version numbers for this library in these files?\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/240392343",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-240392343",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 240392343,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI0MDM5MjM0Mw==",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-17T12:08:30Z",
    "updated_at": "2016-08-17T12:08:30Z",
    "author_association": "CONTRIBUTOR",
    "body": "@mhaseebtariq so the import tests should then work on 3.4 build (which has latest version), and skip on 2.7. pls show the results from travis here \n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/240395910",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-240395910",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 240395910,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI0MDM5NTkxMA==",
    "user": {
      "login": "mhaseebtariq",
      "id": 7199752,
      "node_id": "MDQ6VXNlcjcxOTk3NTI=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7199752?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mhaseebtariq",
      "html_url": "https://github.com/mhaseebtariq",
      "followers_url": "https://api.github.com/users/mhaseebtariq/followers",
      "following_url": "https://api.github.com/users/mhaseebtariq/following{/other_user}",
      "gists_url": "https://api.github.com/users/mhaseebtariq/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mhaseebtariq/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mhaseebtariq/subscriptions",
      "organizations_url": "https://api.github.com/users/mhaseebtariq/orgs",
      "repos_url": "https://api.github.com/users/mhaseebtariq/repos",
      "events_url": "https://api.github.com/users/mhaseebtariq/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mhaseebtariq/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-17T12:27:13Z",
    "updated_at": "2016-08-17T12:27:13Z",
    "author_association": "CONTRIBUTOR",
    "body": "@jreback Even with the correct library version, the test will still be skipped because - The user should be logged in to Google Cloud in the environment the tests are being run. \n\n**partheas** has already successfully tested the functionality on the correct environment.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/240406826",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-240406826",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 240406826,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI0MDQwNjgyNg==",
    "user": {
      "login": "parthea",
      "id": 5184014,
      "node_id": "MDQ6VXNlcjUxODQwMTQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/5184014?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/parthea",
      "html_url": "https://github.com/parthea",
      "followers_url": "https://api.github.com/users/parthea/followers",
      "following_url": "https://api.github.com/users/parthea/following{/other_user}",
      "gists_url": "https://api.github.com/users/parthea/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/parthea/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/parthea/subscriptions",
      "organizations_url": "https://api.github.com/users/parthea/orgs",
      "repos_url": "https://api.github.com/users/parthea/repos",
      "events_url": "https://api.github.com/users/parthea/events{/privacy}",
      "received_events_url": "https://api.github.com/users/parthea/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-17T13:14:41Z",
    "updated_at": "2016-08-17T13:15:07Z",
    "author_association": "CONTRIBUTOR",
    "body": "> partheas has already successfully tested the functionality on the correct environment.\n\nYes. All gbq tests pass.\n\n> This change requires `google-api-python-client==1.5` though.\n\nI've confirmed both `google-api-python-client==1.2` and `google-api-python-client==1.5.1` works\n\nThis feature isn't supported if `oauth2client==1.2`  (that version doesn't have `client.GoogleCredentials`)\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/240412913",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-240412913",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 240412913,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI0MDQxMjkxMw==",
    "user": {
      "login": "mhaseebtariq",
      "id": 7199752,
      "node_id": "MDQ6VXNlcjcxOTk3NTI=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7199752?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mhaseebtariq",
      "html_url": "https://github.com/mhaseebtariq",
      "followers_url": "https://api.github.com/users/mhaseebtariq/followers",
      "following_url": "https://api.github.com/users/mhaseebtariq/following{/other_user}",
      "gists_url": "https://api.github.com/users/mhaseebtariq/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mhaseebtariq/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mhaseebtariq/subscriptions",
      "organizations_url": "https://api.github.com/users/mhaseebtariq/orgs",
      "repos_url": "https://api.github.com/users/mhaseebtariq/repos",
      "events_url": "https://api.github.com/users/mhaseebtariq/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mhaseebtariq/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-17T13:36:58Z",
    "updated_at": "2016-08-17T13:36:58Z",
    "author_association": "CONTRIBUTOR",
    "body": "@parthea this is strange - https://github.com/pydata/pandas/pull/13608/commits/6bbdcdc0a85ab08e8414051034e1409fb3086209\nis failing. This is just a change in the documentation. Would you know what's happening? Thanks!\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/240415255",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-240415255",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 240415255,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI0MDQxNTI1NQ==",
    "user": {
      "login": "parthea",
      "id": 5184014,
      "node_id": "MDQ6VXNlcjUxODQwMTQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/5184014?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/parthea",
      "html_url": "https://github.com/parthea",
      "followers_url": "https://api.github.com/users/parthea/followers",
      "following_url": "https://api.github.com/users/parthea/following{/other_user}",
      "gists_url": "https://api.github.com/users/parthea/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/parthea/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/parthea/subscriptions",
      "organizations_url": "https://api.github.com/users/parthea/orgs",
      "repos_url": "https://api.github.com/users/parthea/repos",
      "events_url": "https://api.github.com/users/parthea/events{/privacy}",
      "received_events_url": "https://api.github.com/users/parthea/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-17T13:44:33Z",
    "updated_at": "2016-08-17T13:44:33Z",
    "author_association": "CONTRIBUTOR",
    "body": "@mhaseebtariq Try adding your forked repository (mhaseebtariq/pandas) to https://travis-ci.org/. Its super easy. Register at https://travis-ci.org/ , then add your forked repository. This will allow you to retry builds to see whether the error is reproducible.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/240659719",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-240659719",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 240659719,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI0MDY1OTcxOQ==",
    "user": {
      "login": "mhaseebtariq",
      "id": 7199752,
      "node_id": "MDQ6VXNlcjcxOTk3NTI=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7199752?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mhaseebtariq",
      "html_url": "https://github.com/mhaseebtariq",
      "followers_url": "https://api.github.com/users/mhaseebtariq/followers",
      "following_url": "https://api.github.com/users/mhaseebtariq/following{/other_user}",
      "gists_url": "https://api.github.com/users/mhaseebtariq/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mhaseebtariq/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mhaseebtariq/subscriptions",
      "organizations_url": "https://api.github.com/users/mhaseebtariq/orgs",
      "repos_url": "https://api.github.com/users/mhaseebtariq/repos",
      "events_url": "https://api.github.com/users/mhaseebtariq/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mhaseebtariq/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-18T08:38:05Z",
    "updated_at": "2016-08-18T08:38:05Z",
    "author_association": "CONTRIBUTOR",
    "body": "Now the tests are passing!\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/240689372",
    "html_url": "https://github.com/pandas-dev/pandas/pull/13608#issuecomment-240689372",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/13608",
    "id": 240689372,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI0MDY4OTM3Mg==",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-18T10:49:51Z",
    "updated_at": "2016-08-18T10:49:51Z",
    "author_association": "CONTRIBUTOR",
    "body": "thanks!\n"
  }
]
