[
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/322900410",
    "html_url": "https://github.com/pandas-dev/pandas/issues/17267#issuecomment-322900410",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/17267",
    "id": 322900410,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMyMjkwMDQxMA==",
    "user": {
      "login": "gfyoung",
      "id": 9273653,
      "node_id": "MDQ6VXNlcjkyNzM2NTM=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/9273653?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gfyoung",
      "html_url": "https://github.com/gfyoung",
      "followers_url": "https://api.github.com/users/gfyoung/followers",
      "following_url": "https://api.github.com/users/gfyoung/following{/other_user}",
      "gists_url": "https://api.github.com/users/gfyoung/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gfyoung/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gfyoung/subscriptions",
      "organizations_url": "https://api.github.com/users/gfyoung/orgs",
      "repos_url": "https://api.github.com/users/gfyoung/repos",
      "events_url": "https://api.github.com/users/gfyoung/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gfyoung/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-08-16T21:10:36Z",
    "updated_at": "2017-08-16T21:10:36Z",
    "author_association": "MEMBER",
    "body": "@zhhhaolong : Thanks for reporting this issue!  Unfortunately, we can't replicate this problem with out the file on hand.  Do you mind attaching it to this issue (as a ZIP) OR providing a link to shared document where we can access it?\r\n\r\nAlso, if you could provide the output of `pd.show_versions` in your original issue, that would be great."
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/322909510",
    "html_url": "https://github.com/pandas-dev/pandas/issues/17267#issuecomment-322909510",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/17267",
    "id": 322909510,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMyMjkwOTUxMA==",
    "user": {
      "login": "TomAugspurger",
      "id": 1312546,
      "node_id": "MDQ6VXNlcjEzMTI1NDY=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1312546?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/TomAugspurger",
      "html_url": "https://github.com/TomAugspurger",
      "followers_url": "https://api.github.com/users/TomAugspurger/followers",
      "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
      "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
      "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
      "repos_url": "https://api.github.com/users/TomAugspurger/repos",
      "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
      "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-08-16T21:49:30Z",
    "updated_at": "2017-08-16T21:49:30Z",
    "author_association": "CONTRIBUTOR",
    "body": "@zhhhaolong can you check to see if pytables lets you create groups with the same name as a table?"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/323023756",
    "html_url": "https://github.com/pandas-dev/pandas/issues/17267#issuecomment-323023756",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/17267",
    "id": 323023756,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMyMzAyMzc1Ng==",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-08-17T09:55:10Z",
    "updated_at": "2017-08-17T09:55:10Z",
    "author_association": "CONTRIBUTOR",
    "body": "pls see the documentation : http://pandas.pydata.org/pandas-docs/stable/io.html#hierarchical-keys\r\n\r\n> Removal operations can remove everything in the sub-store and BELOW, so be careful.\r\n\r\nThe 2nd operation by definition is a removal operation, then a new operation. You can achieve what you want by reversign the orderings.\r\n\r\nI suppose this could be fixed by a community pull request. \r\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/323057405",
    "html_url": "https://github.com/pandas-dev/pandas/issues/17267#issuecomment-323057405",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/17267",
    "id": 323057405,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMyMzA1NzQwNQ==",
    "user": {
      "login": "zhhhaolong",
      "id": 9661819,
      "node_id": "MDQ6VXNlcjk2NjE4MTk=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/9661819?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zhhhaolong",
      "html_url": "https://github.com/zhhhaolong",
      "followers_url": "https://api.github.com/users/zhhhaolong/followers",
      "following_url": "https://api.github.com/users/zhhhaolong/following{/other_user}",
      "gists_url": "https://api.github.com/users/zhhhaolong/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zhhhaolong/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zhhhaolong/subscriptions",
      "organizations_url": "https://api.github.com/users/zhhhaolong/orgs",
      "repos_url": "https://api.github.com/users/zhhhaolong/repos",
      "events_url": "https://api.github.com/users/zhhhaolong/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zhhhaolong/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-08-17T12:25:49Z",
    "updated_at": "2017-08-17T12:25:49Z",
    "author_association": "NONE",
    "body": "Thanks @gfyoung, @TomAugspurger and @jreback for your responses. As @jreback explained, if the to_hdf commend amounts to following pseudo code:\r\n\r\nif key in store:\r\n   store.remove(key)\r\nstore[key]=added table\r\n\r\nThen the behavior is explained. \r\n\r\nHowever, this might not be the intended consequences? \r\n\r\nAs for my test file, it is attached @gfyoung \r\n[test.zip](https://github.com/pandas-dev/pandas/files/1231229/test.zip)\r\n"
  }
]
