[
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/380785456",
    "html_url": "https://github.com/pandas-dev/pandas/issues/20666#issuecomment-380785456",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/20666",
    "id": 380785456,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM4MDc4NTQ1Ng==",
    "user": {
      "login": "TomAugspurger",
      "id": 1312546,
      "node_id": "MDQ6VXNlcjEzMTI1NDY=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1312546?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/TomAugspurger",
      "html_url": "https://github.com/TomAugspurger",
      "followers_url": "https://api.github.com/users/TomAugspurger/followers",
      "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
      "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
      "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
      "repos_url": "https://api.github.com/users/TomAugspurger/repos",
      "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
      "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-12T12:20:08Z",
    "updated_at": "2018-04-12T12:20:25Z",
    "author_association": "CONTRIBUTOR",
    "body": "Is there anything pandas should do here? From my brief skim of https://github.com/pypa/pip/issues/5171 it's not clear what we should change (if anything).\r\n\r\nNote, we just followed SciPy here: https://github.com/scipy/scipy/blob/master/pyproject.toml, so they'll have similar issues."
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/380787922",
    "html_url": "https://github.com/pandas-dev/pandas/issues/20666#issuecomment-380787922",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/20666",
    "id": 380787922,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM4MDc4NzkyMg==",
    "user": {
      "login": "davidjlloyd",
      "id": 34747193,
      "node_id": "MDQ6VXNlcjM0NzQ3MTkz",
      "avatar_url": "https://avatars2.githubusercontent.com/u/34747193?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/davidjlloyd",
      "html_url": "https://github.com/davidjlloyd",
      "followers_url": "https://api.github.com/users/davidjlloyd/followers",
      "following_url": "https://api.github.com/users/davidjlloyd/following{/other_user}",
      "gists_url": "https://api.github.com/users/davidjlloyd/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/davidjlloyd/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/davidjlloyd/subscriptions",
      "organizations_url": "https://api.github.com/users/davidjlloyd/orgs",
      "repos_url": "https://api.github.com/users/davidjlloyd/repos",
      "events_url": "https://api.github.com/users/davidjlloyd/events{/privacy}",
      "received_events_url": "https://api.github.com/users/davidjlloyd/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-12T12:29:39Z",
    "updated_at": "2018-04-12T12:29:39Z",
    "author_association": "NONE",
    "body": "Unclear. PyPA are suggesting that the implementation of PEP 518 was premature, but I'm not sure I agree with that. At least having this issue reported here will help people find out what's wrong and how to fix it (for reference, you can somewhat avoid the issue by passing the flag `--no-build-isolation` to Pip 10). I think it is up to Pandas contributors to decide what, if any, action should be taken in response to this upcoming issue."
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/380912813",
    "html_url": "https://github.com/pandas-dev/pandas/issues/20666#issuecomment-380912813",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/20666",
    "id": 380912813,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM4MDkxMjgxMw==",
    "user": {
      "login": "TomAugspurger",
      "id": 1312546,
      "node_id": "MDQ6VXNlcjEzMTI1NDY=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1312546?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/TomAugspurger",
      "html_url": "https://github.com/TomAugspurger",
      "followers_url": "https://api.github.com/users/TomAugspurger/followers",
      "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
      "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
      "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
      "repos_url": "https://api.github.com/users/TomAugspurger/repos",
      "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
      "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-12T19:07:17Z",
    "updated_at": "2018-04-12T19:07:17Z",
    "author_association": "CONTRIBUTOR",
    "body": "Yes, thanks for raising the issue.\n\nI suspect that others know more about what the proper thing to do here is.\nWe're happy to just follow best practices.\n\n\nOn Thu, Apr 12, 2018 at 7:29 AM, davidjlloyd <notifications@github.com>\nwrote:\n\n> Unclear. PyPA are suggesting that the implementation of PEP 518 was\n> premature, but I'm not sure I agree with that. At least having this issue\n> reported here will help people find out what's wrong and how to fix it (for\n> reference, you can somewhat avoid the issue by passing the flag\n> --no-build-isolation to Pip 10). I think it is up to Pandas contributors\n> to decide what, if any, action should be taken in response to this upcoming\n> issue.\n>\n> â€”\n> You are receiving this because you commented.\n> Reply to this email directly, view it on GitHub\n> <https://github.com/pandas-dev/pandas/issues/20666#issuecomment-380787922>,\n> or mute the thread\n> <https://github.com/notifications/unsubscribe-auth/ABQHIvUWWcxvbzhBn2qHqHiY3Y43ULwRks5tn0i7gaJpZM4TRrZh>\n> .\n>\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/381939653",
    "html_url": "https://github.com/pandas-dev/pandas/issues/20666#issuecomment-381939653",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/20666",
    "id": 381939653,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM4MTkzOTY1Mw==",
    "user": {
      "login": "dinapappor",
      "id": 5546957,
      "node_id": "MDQ6VXNlcjU1NDY5NTc=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/5546957?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dinapappor",
      "html_url": "https://github.com/dinapappor",
      "followers_url": "https://api.github.com/users/dinapappor/followers",
      "following_url": "https://api.github.com/users/dinapappor/following{/other_user}",
      "gists_url": "https://api.github.com/users/dinapappor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dinapappor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dinapappor/subscriptions",
      "organizations_url": "https://api.github.com/users/dinapappor/orgs",
      "repos_url": "https://api.github.com/users/dinapappor/repos",
      "events_url": "https://api.github.com/users/dinapappor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dinapappor/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-17T10:29:25Z",
    "updated_at": "2018-04-17T11:51:24Z",
    "author_association": "NONE",
    "body": "This also happens in a virtualenv with python 3.6 (no pypy) on FreeBSD 11.1 (fully patched)."
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/381983264",
    "html_url": "https://github.com/pandas-dev/pandas/issues/20666#issuecomment-381983264",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/20666",
    "id": 381983264,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM4MTk4MzI2NA==",
    "user": {
      "login": "jorisvandenbossche",
      "id": 1020496,
      "node_id": "MDQ6VXNlcjEwMjA0OTY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1020496?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jorisvandenbossche",
      "html_url": "https://github.com/jorisvandenbossche",
      "followers_url": "https://api.github.com/users/jorisvandenbossche/followers",
      "following_url": "https://api.github.com/users/jorisvandenbossche/following{/other_user}",
      "gists_url": "https://api.github.com/users/jorisvandenbossche/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jorisvandenbossche/subscriptions",
      "organizations_url": "https://api.github.com/users/jorisvandenbossche/orgs",
      "repos_url": "https://api.github.com/users/jorisvandenbossche/repos",
      "events_url": "https://api.github.com/users/jorisvandenbossche/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jorisvandenbossche/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-17T12:59:47Z",
    "updated_at": "2018-04-17T12:59:47Z",
    "author_association": "MEMBER",
    "body": "I think this issue is another reason to remove `pyproject.toml` for now: https://github.com/pandas-dev/pandas/pull/20718 (that will of course only solve it once 0.23.0 is out)"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/382033319",
    "html_url": "https://github.com/pandas-dev/pandas/issues/20666#issuecomment-382033319",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/20666",
    "id": 382033319,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM4MjAzMzMxOQ==",
    "user": {
      "login": "diraol",
      "id": 192702,
      "node_id": "MDQ6VXNlcjE5MjcwMg==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/192702?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/diraol",
      "html_url": "https://github.com/diraol",
      "followers_url": "https://api.github.com/users/diraol/followers",
      "following_url": "https://api.github.com/users/diraol/following{/other_user}",
      "gists_url": "https://api.github.com/users/diraol/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/diraol/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/diraol/subscriptions",
      "organizations_url": "https://api.github.com/users/diraol/orgs",
      "repos_url": "https://api.github.com/users/diraol/repos",
      "events_url": "https://api.github.com/users/diraol/events{/privacy}",
      "received_events_url": "https://api.github.com/users/diraol/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-17T15:23:48Z",
    "updated_at": "2018-04-17T15:23:48Z",
    "author_association": "NONE",
    "body": "This also happens on `Debian 9`, `python 3.6` `pip 10.0.0`, `setuptools 39.0.1` and `wheel 0.31.0` (linux) while trying to install without binaries."
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/382044250",
    "html_url": "https://github.com/pandas-dev/pandas/issues/20666#issuecomment-382044250",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/20666",
    "id": 382044250,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM4MjA0NDI1MA==",
    "user": {
      "login": "jorisvandenbossche",
      "id": 1020496,
      "node_id": "MDQ6VXNlcjEwMjA0OTY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1020496?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jorisvandenbossche",
      "html_url": "https://github.com/jorisvandenbossche",
      "followers_url": "https://api.github.com/users/jorisvandenbossche/followers",
      "following_url": "https://api.github.com/users/jorisvandenbossche/following{/other_user}",
      "gists_url": "https://api.github.com/users/jorisvandenbossche/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jorisvandenbossche/subscriptions",
      "organizations_url": "https://api.github.com/users/jorisvandenbossche/orgs",
      "repos_url": "https://api.github.com/users/jorisvandenbossche/repos",
      "events_url": "https://api.github.com/users/jorisvandenbossche/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jorisvandenbossche/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-17T15:52:14Z",
    "updated_at": "2018-04-17T15:52:14Z",
    "author_association": "MEMBER",
    "body": "You can pass `--no-build-isolation` flag to pip to avoid this problem (https://github.com/pypa/pip/issues/5229)."
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/382234589",
    "html_url": "https://github.com/pandas-dev/pandas/issues/20666#issuecomment-382234589",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/20666",
    "id": 382234589,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM4MjIzNDU4OQ==",
    "user": {
      "login": "dinapappor",
      "id": 5546957,
      "node_id": "MDQ6VXNlcjU1NDY5NTc=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/5546957?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dinapappor",
      "html_url": "https://github.com/dinapappor",
      "followers_url": "https://api.github.com/users/dinapappor/followers",
      "following_url": "https://api.github.com/users/dinapappor/following{/other_user}",
      "gists_url": "https://api.github.com/users/dinapappor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dinapappor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dinapappor/subscriptions",
      "organizations_url": "https://api.github.com/users/dinapappor/orgs",
      "repos_url": "https://api.github.com/users/dinapappor/repos",
      "events_url": "https://api.github.com/users/dinapappor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dinapappor/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-18T02:52:36Z",
    "updated_at": "2018-04-18T02:52:36Z",
    "author_association": "NONE",
    "body": "Passing `--no-build-isolation` yields a cc error for me."
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/382253665",
    "html_url": "https://github.com/pandas-dev/pandas/issues/20666#issuecomment-382253665",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/20666",
    "id": 382253665,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM4MjI1MzY2NQ==",
    "user": {
      "login": "TomAugspurger",
      "id": 1312546,
      "node_id": "MDQ6VXNlcjEzMTI1NDY=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1312546?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/TomAugspurger",
      "html_url": "https://github.com/TomAugspurger",
      "followers_url": "https://api.github.com/users/TomAugspurger/followers",
      "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
      "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
      "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
      "repos_url": "https://api.github.com/users/TomAugspurger/repos",
      "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
      "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-18T04:14:31Z",
    "updated_at": "2018-04-18T04:14:31Z",
    "author_association": "CONTRIBUTOR",
    "body": "If you arenâ€™t using binaries then youâ€™ll need a compiler.\n\n________________________________\nFrom: Andreas Anderssson <notifications@github.com>\nSent: Tuesday, April 17, 2018 9:52:43 PM\nTo: pandas-dev/pandas\nCc: Tom Augspurger; Comment\nSubject: Re: [pandas-dev/pandas] Installation of Pandas in Pip v10.0.0b2 on PyPy fails (#20666)\n\n\nPassing --no-build-isolation yields a cc error for me.\n\nâ€”\nYou are receiving this because you commented.\nReply to this email directly, view it on GitHub<https://github.com/pandas-dev/pandas/issues/20666#issuecomment-382234589>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ABQHIsy4HkAFTVoqhChD9sk3crfM18NXks5tpqp7gaJpZM4TRrZh>.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/382255271",
    "html_url": "https://github.com/pandas-dev/pandas/issues/20666#issuecomment-382255271",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/20666",
    "id": 382255271,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM4MjI1NTI3MQ==",
    "user": {
      "login": "dinapappor",
      "id": 5546957,
      "node_id": "MDQ6VXNlcjU1NDY5NTc=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/5546957?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dinapappor",
      "html_url": "https://github.com/dinapappor",
      "followers_url": "https://api.github.com/users/dinapappor/followers",
      "following_url": "https://api.github.com/users/dinapappor/following{/other_user}",
      "gists_url": "https://api.github.com/users/dinapappor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dinapappor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dinapappor/subscriptions",
      "organizations_url": "https://api.github.com/users/dinapappor/orgs",
      "repos_url": "https://api.github.com/users/dinapappor/repos",
      "events_url": "https://api.github.com/users/dinapappor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dinapappor/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-18T04:22:16Z",
    "updated_at": "2018-04-18T04:22:16Z",
    "author_association": "NONE",
    "body": "I do have a compiler installed (clang). Which is infact successfully used\nby other python dependencies that needs to be compiled. Let me get back\nlater with the full error message.\n\nDen ons 18 apr. 2018 06:14Tom Augspurger <notifications@github.com> skrev:\n\n> If you arenâ€™t using binaries then youâ€™ll need a compiler.\n>\n> ________________________________\n> From: Andreas Anderssson <notifications@github.com>\n> Sent: Tuesday, April 17, 2018 9:52:43 PM\n> To: pandas-dev/pandas\n> Cc: Tom Augspurger; Comment\n> Subject: Re: [pandas-dev/pandas] Installation of Pandas in Pip v10.0.0b2\n> on PyPy fails (#20666)\n>\n>\n> Passing --no-build-isolation yields a cc error for me.\n>\n> â€”\n> You are receiving this because you commented.\n> Reply to this email directly, view it on GitHub<\n> https://github.com/pandas-dev/pandas/issues/20666#issuecomment-382234589>,\n> or mute the thread<\n> https://github.com/notifications/unsubscribe-auth/ABQHIsy4HkAFTVoqhChD9sk3crfM18NXks5tpqp7gaJpZM4TRrZh\n> >.\n>\n> â€”\n> You are receiving this because you commented.\n> Reply to this email directly, view it on GitHub\n> <https://github.com/pandas-dev/pandas/issues/20666#issuecomment-382253665>,\n> or mute the thread\n> <https://github.com/notifications/unsubscribe-auth/AFSjzaapNO0h9uY8yUihrXaA2ZwOXZuLks5tpr22gaJpZM4TRrZh>\n> .\n>\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/382367172",
    "html_url": "https://github.com/pandas-dev/pandas/issues/20666#issuecomment-382367172",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/20666",
    "id": 382367172,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM4MjM2NzE3Mg==",
    "user": {
      "login": "dinapappor",
      "id": 5546957,
      "node_id": "MDQ6VXNlcjU1NDY5NTc=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/5546957?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dinapappor",
      "html_url": "https://github.com/dinapappor",
      "followers_url": "https://api.github.com/users/dinapappor/followers",
      "following_url": "https://api.github.com/users/dinapappor/following{/other_user}",
      "gists_url": "https://api.github.com/users/dinapappor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dinapappor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dinapappor/subscriptions",
      "organizations_url": "https://api.github.com/users/dinapappor/orgs",
      "repos_url": "https://api.github.com/users/dinapappor/repos",
      "events_url": "https://api.github.com/users/dinapappor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dinapappor/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-18T12:20:23Z",
    "updated_at": "2018-04-18T12:20:23Z",
    "author_association": "NONE",
    "body": "This is the error I am getting:\r\n\r\n```\r\ndistutils.errors.LinkError: Command \"cc /tmp/tmp86b2sak0/tmp/tmp86b2sak0/source.o -L/usr/local/lib -lblas -o /tmp/tmp86b2sak0/a.out\" failed with exit status 1\r\n```"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/382372369",
    "html_url": "https://github.com/pandas-dev/pandas/issues/20666#issuecomment-382372369",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/20666",
    "id": 382372369,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM4MjM3MjM2OQ==",
    "user": {
      "login": "dinapappor",
      "id": 5546957,
      "node_id": "MDQ6VXNlcjU1NDY5NTc=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/5546957?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dinapappor",
      "html_url": "https://github.com/dinapappor",
      "followers_url": "https://api.github.com/users/dinapappor/followers",
      "following_url": "https://api.github.com/users/dinapappor/following{/other_user}",
      "gists_url": "https://api.github.com/users/dinapappor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dinapappor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dinapappor/subscriptions",
      "organizations_url": "https://api.github.com/users/dinapappor/orgs",
      "repos_url": "https://api.github.com/users/dinapappor/repos",
      "events_url": "https://api.github.com/users/dinapappor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dinapappor/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-18T12:40:30Z",
    "updated_at": "2018-04-18T12:40:30Z",
    "author_association": "NONE",
    "body": "The previous comment was actually because I already had numpy installed as an os level package in FreeBSD. Seems to work with `--no-build-isolation`."
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/383281554",
    "html_url": "https://github.com/pandas-dev/pandas/issues/20666#issuecomment-383281554",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/20666",
    "id": 383281554,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM4MzI4MTU1NA==",
    "user": {
      "login": "jorisvandenbossche",
      "id": 1020496,
      "node_id": "MDQ6VXNlcjEwMjA0OTY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1020496?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jorisvandenbossche",
      "html_url": "https://github.com/jorisvandenbossche",
      "followers_url": "https://api.github.com/users/jorisvandenbossche/followers",
      "following_url": "https://api.github.com/users/jorisvandenbossche/following{/other_user}",
      "gists_url": "https://api.github.com/users/jorisvandenbossche/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jorisvandenbossche/subscriptions",
      "organizations_url": "https://api.github.com/users/jorisvandenbossche/orgs",
      "repos_url": "https://api.github.com/users/jorisvandenbossche/repos",
      "events_url": "https://api.github.com/users/jorisvandenbossche/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jorisvandenbossche/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-21T09:41:25Z",
    "updated_at": "2018-04-21T09:41:25Z",
    "author_association": "MEMBER",
    "body": "I made an overview issue with the problems: https://github.com/pandas-dev/pandas/issues/20775, so let's close this one"
  }
]
