[
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/464602837",
    "html_url": "https://github.com/pandas-dev/pandas/issues/25332#issuecomment-464602837",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/25332",
    "id": 464602837,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2NDYwMjgzNw==",
    "user": {
      "login": "gfyoung",
      "id": 9273653,
      "node_id": "MDQ6VXNlcjkyNzM2NTM=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/9273653?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gfyoung",
      "html_url": "https://github.com/gfyoung",
      "followers_url": "https://api.github.com/users/gfyoung/followers",
      "following_url": "https://api.github.com/users/gfyoung/following{/other_user}",
      "gists_url": "https://api.github.com/users/gfyoung/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gfyoung/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gfyoung/subscriptions",
      "organizations_url": "https://api.github.com/users/gfyoung/orgs",
      "repos_url": "https://api.github.com/users/gfyoung/repos",
      "events_url": "https://api.github.com/users/gfyoung/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gfyoung/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-02-18T06:30:24Z",
    "updated_at": "2019-02-18T06:30:24Z",
    "author_association": "MEMBER",
    "body": "A very odd regression indeed, but a regression nonetheless and for a reasonable intention IMO."
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/464672417",
    "html_url": "https://github.com/pandas-dev/pandas/issues/25332#issuecomment-464672417",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/25332",
    "id": 464672417,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2NDY3MjQxNw==",
    "user": {
      "login": "gfyoung",
      "id": 9273653,
      "node_id": "MDQ6VXNlcjkyNzM2NTM=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/9273653?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gfyoung",
      "html_url": "https://github.com/gfyoung",
      "followers_url": "https://api.github.com/users/gfyoung/followers",
      "following_url": "https://api.github.com/users/gfyoung/following{/other_user}",
      "gists_url": "https://api.github.com/users/gfyoung/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gfyoung/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gfyoung/subscriptions",
      "organizations_url": "https://api.github.com/users/gfyoung/orgs",
      "repos_url": "https://api.github.com/users/gfyoung/repos",
      "events_url": "https://api.github.com/users/gfyoung/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gfyoung/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-02-18T10:18:08Z",
    "updated_at": "2019-02-18T10:21:15Z",
    "author_association": "MEMBER",
    "body": "cc @jreback \r\n\r\nThis stems from #24541 in which `MagicMock` now gets passed into `pandas_dtype` from when `is_timedelta64_dtype` is called (this function is called as well prior to this commit, but the object would not get passed to the central `pandas_dtype` function).\r\n\r\nThe breaking logic is here:\r\n\r\nhttps://github.com/pandas-dev/pandas/blob/659e0ca/pandas/core/dtypes/common.py#L2036-L2043\r\n\r\nUnfortunately, `numpy` dtypes do not play nice with `MagicMock`.  In fact, you can replicate the segfault yourself by just doing this:\r\n\r\n~~~python\r\nfrom unittest.mock import MagicMock\r\n\r\nimport numpy as np\r\n\r\nnp.dtype(MagicMock())\r\n~~~\r\n\r\n@roachlord : Perhaps this might be worthwhile to bring up as an issue on the `numpy` side as well."
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/464712896",
    "html_url": "https://github.com/pandas-dev/pandas/issues/25332#issuecomment-464712896",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/25332",
    "id": 464712896,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2NDcxMjg5Ng==",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-02-18T12:23:11Z",
    "updated_at": "2019-02-18T12:23:11Z",
    "author_association": "CONTRIBUTOR",
    "body": "this is not supported in any way; it may have happened to work before"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/464839603",
    "html_url": "https://github.com/pandas-dev/pandas/issues/25332#issuecomment-464839603",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/25332",
    "id": 464839603,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2NDgzOTYwMw==",
    "user": {
      "login": "gfyoung",
      "id": 9273653,
      "node_id": "MDQ6VXNlcjkyNzM2NTM=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/9273653?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gfyoung",
      "html_url": "https://github.com/gfyoung",
      "followers_url": "https://api.github.com/users/gfyoung/followers",
      "following_url": "https://api.github.com/users/gfyoung/following{/other_user}",
      "gists_url": "https://api.github.com/users/gfyoung/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gfyoung/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gfyoung/subscriptions",
      "organizations_url": "https://api.github.com/users/gfyoung/orgs",
      "repos_url": "https://api.github.com/users/gfyoung/repos",
      "events_url": "https://api.github.com/users/gfyoung/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gfyoung/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-02-18T18:41:24Z",
    "updated_at": "2019-02-18T18:41:24Z",
    "author_association": "MEMBER",
    "body": "@jreback : Fair enough. üëç \r\n\r\n@roachlord : I see you are making some headway with your issue to `numpy`.  If that gets resolved, that would also resolve the issue on our end (I think?), so perhaps that would be your best route for now."
  }
]
