[
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/39958126",
    "html_url": "https://github.com/pandas-dev/pandas/issues/6846#issuecomment-39958126",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/6846",
    "id": 39958126,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM5OTU4MTI2",
    "user": {
      "login": "jorisvandenbossche",
      "id": 1020496,
      "node_id": "MDQ6VXNlcjEwMjA0OTY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1020496?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jorisvandenbossche",
      "html_url": "https://github.com/jorisvandenbossche",
      "followers_url": "https://api.github.com/users/jorisvandenbossche/followers",
      "following_url": "https://api.github.com/users/jorisvandenbossche/following{/other_user}",
      "gists_url": "https://api.github.com/users/jorisvandenbossche/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jorisvandenbossche/subscriptions",
      "organizations_url": "https://api.github.com/users/jorisvandenbossche/orgs",
      "repos_url": "https://api.github.com/users/jorisvandenbossche/repos",
      "events_url": "https://api.github.com/users/jorisvandenbossche/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jorisvandenbossche/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-04-09T12:33:25Z",
    "updated_at": "2014-04-09T12:33:25Z",
    "author_association": "MEMBER",
    "body": "See also #6843.\n\nI can't try to reproduce it at the moment (I get `OverflowError: Python int too large to convert to C long` on python 2.7, windows, 64 bit, I think something windows-specific (C long is 32 bit on windows)).\n\nBut can you try it also with the new sqlalchemy-based functions? It should be something like:\n\n```\nfrom sqlalchemy import create_engine\nengine = create_engine('sqlite:////tmp/bidulechouette.db')\ndata.to_sql(\"DATA\", engine, if_exists=\"replace\", index=False)\n```\n\nto see if you have the same issue with this.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/39958712",
    "html_url": "https://github.com/pandas-dev/pandas/issues/6846#issuecomment-39958712",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/6846",
    "id": 39958712,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM5OTU4NzEy",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-04-09T12:40:30Z",
    "updated_at": "2014-04-09T12:40:50Z",
    "author_association": "CONTRIBUTOR",
    "body": "this is for windows:\n\nnumpy on windows is not friendly to large ints with the random number generation. might be a bug, as their is no way to specify the dtype upfront (e.g. randint doesn't take a dtype argument). could be an implementation detail as well.\n\nso I think you would have to generate int32's cast them to int64 then multiply to get int64 like numbers (which pandas will handle).\n\n```\n>>> np.random.randint(2**63-1,size=100)\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"mtrand.pyx\", line 871, in mtrand.RandomState.randint (numpy\\random\\mtrand\\mtrand.c:6682)\nOverflowError: Python int too large to convert to C long\n\n>>> np.random.randint(2**31-1,size=100)\narray([1065151596,  141587709, 1034731056, 1421678991, 1113510421,\n       1053591656,  721945385,  417353460,  588311441,  451124932,\n       2011103288,  606400194, 1767870596, 1577034881,  801116609,\n       1094153300,  681848258, 1216074099,  828001710, 1818981627,\n        583590097, 1893057734, 2041021821, 1719114523,  659638699,\n         36901870, 1500212655,   80923766, 1147783744, 1802598765,\n        148074008,  637763026, 2105303772, 1512947348, 1699075859,\n        842315446, 1365873318,  820098773,  676695949, 1474271470,\n        335374748, 1477530337, 1537800347,   87529923,  516659836,\n       1551506257, 1743913044, 1156954863, 1286249176, 1279615765,\n       1740947158,  448293258, 1524004071, 1527588882,  795421749,\n       1231177972,  264830723,  589977924,  762902232, 1805756724,\n        696292676,  915029891, 1311767606,  247202537, 1929326874,\n       1238932552, 2026394145,  394577189, 1241699925,  910466670,\n       1911660830, 1717398704,  761388787, 1527405720, 1132149302,\n        930729795, 1350701423,   50980838, 1224099292,  705686236,\n       1529564451,  747506807, 1142508936,  224622576, 1217950640,\n       1208551918,  365819633,  456296798,  715871164, 1228926134,\n       2030700788, 1192490214, 1276642215, 1186011869, 1479536059,\n        334653481, 1961647202, 1838092157,  645948253, 1868626295])\n```\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/39960058",
    "html_url": "https://github.com/pandas-dev/pandas/issues/6846#issuecomment-39960058",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/6846",
    "id": 39960058,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM5OTYwMDU4",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-04-09T12:55:13Z",
    "updated_at": "2014-04-09T12:55:13Z",
    "author_association": "CONTRIBUTOR",
    "body": "this DOES work with @jorisvandenbossche method (python 3.4,numpy 1.8, on 64-bit linux), maybe a problem with sqlite3 dtype conversion of int64's (on the legacy)?\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/39962143",
    "html_url": "https://github.com/pandas-dev/pandas/issues/6846#issuecomment-39962143",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/6846",
    "id": 39962143,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM5OTYyMTQz",
    "user": {
      "login": "jorisvandenbossche",
      "id": 1020496,
      "node_id": "MDQ6VXNlcjEwMjA0OTY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1020496?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jorisvandenbossche",
      "html_url": "https://github.com/jorisvandenbossche",
      "followers_url": "https://api.github.com/users/jorisvandenbossche/followers",
      "following_url": "https://api.github.com/users/jorisvandenbossche/following{/other_user}",
      "gists_url": "https://api.github.com/users/jorisvandenbossche/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jorisvandenbossche/subscriptions",
      "organizations_url": "https://api.github.com/users/jorisvandenbossche/orgs",
      "repos_url": "https://api.github.com/users/jorisvandenbossche/repos",
      "events_url": "https://api.github.com/users/jorisvandenbossche/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jorisvandenbossche/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-04-09T13:17:52Z",
    "updated_at": "2014-04-09T13:17:52Z",
    "author_association": "MEMBER",
    "body": "I can't reproduce this on Windows (python 2.7, 64-bit), but both with the legacy and new slqalchemy method (using the conversion of int32 to int64 and multiplying as suggested by @jreback above).\n\nThe problem with the database that is not deleted properly, do you also have this with other tables (eg with just a toy example with small values)? Or does it only occur with this example with these large values/dtype problem?\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/39964577",
    "html_url": "https://github.com/pandas-dev/pandas/issues/6846#issuecomment-39964577",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/6846",
    "id": 39964577,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM5OTY0NTc3",
    "user": {
      "login": "Acanthostega",
      "id": 4039200,
      "node_id": "MDQ6VXNlcjQwMzkyMDA=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/4039200?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Acanthostega",
      "html_url": "https://github.com/Acanthostega",
      "followers_url": "https://api.github.com/users/Acanthostega/followers",
      "following_url": "https://api.github.com/users/Acanthostega/following{/other_user}",
      "gists_url": "https://api.github.com/users/Acanthostega/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Acanthostega/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Acanthostega/subscriptions",
      "organizations_url": "https://api.github.com/users/Acanthostega/orgs",
      "repos_url": "https://api.github.com/users/Acanthostega/repos",
      "events_url": "https://api.github.com/users/Acanthostega/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Acanthostega/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-04-09T13:40:57Z",
    "updated_at": "2014-04-09T13:40:57Z",
    "author_association": "CONTRIBUTOR",
    "body": "I confirm that it works with the new SQLAlchemy method, but not with the legacy one.\n\nThis is not a specific problem to long integers (int64) since I can reproduce the problem with 2**8 instead of 2**63-1.\n\nIf I don't close the return of the connect function of sqlite3 in the middle, data seems to be read in the memory. But once the ipython console is closed, the database file is still empty (but with table structure).\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/39964799",
    "html_url": "https://github.com/pandas-dev/pandas/issues/6846#issuecomment-39964799",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/6846",
    "id": 39964799,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM5OTY0Nzk5",
    "user": {
      "login": "cpcloud",
      "id": 417981,
      "node_id": "MDQ6VXNlcjQxNzk4MQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/417981?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cpcloud",
      "html_url": "https://github.com/cpcloud",
      "followers_url": "https://api.github.com/users/cpcloud/followers",
      "following_url": "https://api.github.com/users/cpcloud/following{/other_user}",
      "gists_url": "https://api.github.com/users/cpcloud/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cpcloud/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cpcloud/subscriptions",
      "organizations_url": "https://api.github.com/users/cpcloud/orgs",
      "repos_url": "https://api.github.com/users/cpcloud/repos",
      "events_url": "https://api.github.com/users/cpcloud/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cpcloud/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-04-09T13:43:04Z",
    "updated_at": "2014-04-09T13:43:04Z",
    "author_association": "MEMBER",
    "body": "@Acanthostega can you try by just writing a small test case and running `nosetests the_test.py` to see if there's an ipython issue? thx\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/39966670",
    "html_url": "https://github.com/pandas-dev/pandas/issues/6846#issuecomment-39966670",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/6846",
    "id": 39966670,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM5OTY2Njcw",
    "user": {
      "login": "Acanthostega",
      "id": 4039200,
      "node_id": "MDQ6VXNlcjQwMzkyMDA=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/4039200?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Acanthostega",
      "html_url": "https://github.com/Acanthostega",
      "followers_url": "https://api.github.com/users/Acanthostega/followers",
      "following_url": "https://api.github.com/users/Acanthostega/following{/other_user}",
      "gists_url": "https://api.github.com/users/Acanthostega/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Acanthostega/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Acanthostega/subscriptions",
      "organizations_url": "https://api.github.com/users/Acanthostega/orgs",
      "repos_url": "https://api.github.com/users/Acanthostega/repos",
      "events_url": "https://api.github.com/users/Acanthostega/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Acanthostega/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-04-09T13:59:15Z",
    "updated_at": "2014-04-09T13:59:15Z",
    "author_association": "CONTRIBUTOR",
    "body": "I tried with nosetests and \"simple\" python interpreter, but same result...\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/39966849",
    "html_url": "https://github.com/pandas-dev/pandas/issues/6846#issuecomment-39966849",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/6846",
    "id": 39966849,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM5OTY2ODQ5",
    "user": {
      "login": "jorisvandenbossche",
      "id": 1020496,
      "node_id": "MDQ6VXNlcjEwMjA0OTY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1020496?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jorisvandenbossche",
      "html_url": "https://github.com/jorisvandenbossche",
      "followers_url": "https://api.github.com/users/jorisvandenbossche/followers",
      "following_url": "https://api.github.com/users/jorisvandenbossche/following{/other_user}",
      "gists_url": "https://api.github.com/users/jorisvandenbossche/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jorisvandenbossche/subscriptions",
      "organizations_url": "https://api.github.com/users/jorisvandenbossche/orgs",
      "repos_url": "https://api.github.com/users/jorisvandenbossche/repos",
      "events_url": "https://api.github.com/users/jorisvandenbossche/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jorisvandenbossche/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-04-09T14:00:49Z",
    "updated_at": "2014-04-09T14:00:49Z",
    "author_association": "MEMBER",
    "body": "@Acanthostega Can you post the test you used?\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/39967673",
    "html_url": "https://github.com/pandas-dev/pandas/issues/6846#issuecomment-39967673",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/6846",
    "id": 39967673,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM5OTY3Njcz",
    "user": {
      "login": "Acanthostega",
      "id": 4039200,
      "node_id": "MDQ6VXNlcjQwMzkyMDA=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/4039200?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Acanthostega",
      "html_url": "https://github.com/Acanthostega",
      "followers_url": "https://api.github.com/users/Acanthostega/followers",
      "following_url": "https://api.github.com/users/Acanthostega/following{/other_user}",
      "gists_url": "https://api.github.com/users/Acanthostega/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Acanthostega/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Acanthostega/subscriptions",
      "organizations_url": "https://api.github.com/users/Acanthostega/orgs",
      "repos_url": "https://api.github.com/users/Acanthostega/repos",
      "events_url": "https://api.github.com/users/Acanthostega/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Acanthostega/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-04-09T14:07:56Z",
    "updated_at": "2014-04-09T14:07:56Z",
    "author_association": "CONTRIBUTOR",
    "body": "``` python\n\n#!/usr/bin/env python3\n#-*- coding: utf-8 -*-\n\nimport pandas as pd\nimport numpy as np\nimport sqlite3\n\ndata = pd.DataFrame(\n    {\n        \"galid\": np.random.randint(2**8, size=100),\n        \"truc\": np.random.rand(100),\n    }\n)\n\nconn = sqlite3.connect(\"/tmp/machinchose.db\")\n\ndata.to_sql(\"DATA\", conn, if_exists=\"replace\", index=False, flavor=\"sqlite\")\n\nconn.close()\nconn = sqlite3.connect(\"/tmp/machinchose.db\")\n\nresult = pd.read_sql(\"SELECT galid FROM DATA;\", conn)\n\nprint(len(result))\n```\n\nI'm not familiar with nosetests so I did a simple script to check the resulting database, and used the python interpreter to check. I can improve the test if you want but I have to read a little the doc before...\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/39967974",
    "html_url": "https://github.com/pandas-dev/pandas/issues/6846#issuecomment-39967974",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/6846",
    "id": 39967974,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM5OTY3OTc0",
    "user": {
      "login": "cpcloud",
      "id": 417981,
      "node_id": "MDQ6VXNlcjQxNzk4MQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/417981?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cpcloud",
      "html_url": "https://github.com/cpcloud",
      "followers_url": "https://api.github.com/users/cpcloud/followers",
      "following_url": "https://api.github.com/users/cpcloud/following{/other_user}",
      "gists_url": "https://api.github.com/users/cpcloud/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cpcloud/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cpcloud/subscriptions",
      "organizations_url": "https://api.github.com/users/cpcloud/orgs",
      "repos_url": "https://api.github.com/users/cpcloud/repos",
      "events_url": "https://api.github.com/users/cpcloud/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cpcloud/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-04-09T14:10:33Z",
    "updated_at": "2014-04-09T14:10:33Z",
    "author_association": "MEMBER",
    "body": "just write a function called `test_database` then run it with `nosetests the_file_containing_test_database.py`\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/39968368",
    "html_url": "https://github.com/pandas-dev/pandas/issues/6846#issuecomment-39968368",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/6846",
    "id": 39968368,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM5OTY4MzY4",
    "user": {
      "login": "jorisvandenbossche",
      "id": 1020496,
      "node_id": "MDQ6VXNlcjEwMjA0OTY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1020496?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jorisvandenbossche",
      "html_url": "https://github.com/jorisvandenbossche",
      "followers_url": "https://api.github.com/users/jorisvandenbossche/followers",
      "following_url": "https://api.github.com/users/jorisvandenbossche/following{/other_user}",
      "gists_url": "https://api.github.com/users/jorisvandenbossche/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jorisvandenbossche/subscriptions",
      "organizations_url": "https://api.github.com/users/jorisvandenbossche/orgs",
      "repos_url": "https://api.github.com/users/jorisvandenbossche/repos",
      "events_url": "https://api.github.com/users/jorisvandenbossche/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jorisvandenbossche/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-04-09T14:13:55Z",
    "updated_at": "2014-04-09T14:13:55Z",
    "author_association": "MEMBER",
    "body": "OK, so I think the problem is not with too large ints, or with mixed dtype or something like that, but with not correctly closing the database connection. \nAs if you don't do the `conn.close()` in the above script, then it works for me.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/39969119",
    "html_url": "https://github.com/pandas-dev/pandas/issues/6846#issuecomment-39969119",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/6846",
    "id": 39969119,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM5OTY5MTE5",
    "user": {
      "login": "Acanthostega",
      "id": 4039200,
      "node_id": "MDQ6VXNlcjQwMzkyMDA=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/4039200?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Acanthostega",
      "html_url": "https://github.com/Acanthostega",
      "followers_url": "https://api.github.com/users/Acanthostega/followers",
      "following_url": "https://api.github.com/users/Acanthostega/following{/other_user}",
      "gists_url": "https://api.github.com/users/Acanthostega/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Acanthostega/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Acanthostega/subscriptions",
      "organizations_url": "https://api.github.com/users/Acanthostega/orgs",
      "repos_url": "https://api.github.com/users/Acanthostega/repos",
      "events_url": "https://api.github.com/users/Acanthostega/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Acanthostega/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-04-09T14:20:37Z",
    "updated_at": "2014-04-09T14:20:37Z",
    "author_association": "CONTRIBUTOR",
    "body": "@jorisvandenbossche So, do you reproduce the problem with closing the connection to the database? Since, if I don't close the `conn`, the data is read in the memory, but nothing is present in the database file.\n\n@cpcloud I rewrote the test:\n\n``` python\n#!/usr/bin/env python3\n#-*- coding: utf-8 -*-\n\nimport pandas as pd\nimport numpy as np\nimport sqlite3\n\ndef test_database():\n    data = pd.DataFrame(\n        {\n            \"galid\": np.random.randint(2**8, size=100),\n            \"truc\": np.random.rand(100),\n        }\n    )\n\n    conn = sqlite3.connect(\"/tmp/machinchose.db\")\n\n    data.to_sql(\"DATA\", conn, if_exists=\"replace\", index=False, flavor=\"sqlite\")\n\n    conn.close()\n    conn = sqlite3.connect(\"/tmp/machinchose.db\")\n\n    result = pd.read_sql(\"SELECT galid FROM DATA;\", conn)\n\n    print(len(result))\n    assert len(result) == len(data)\n```\n\nSame problem.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/39970671",
    "html_url": "https://github.com/pandas-dev/pandas/issues/6846#issuecomment-39970671",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/6846",
    "id": 39970671,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM5OTcwNjcx",
    "user": {
      "login": "jorisvandenbossche",
      "id": 1020496,
      "node_id": "MDQ6VXNlcjEwMjA0OTY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1020496?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jorisvandenbossche",
      "html_url": "https://github.com/jorisvandenbossche",
      "followers_url": "https://api.github.com/users/jorisvandenbossche/followers",
      "following_url": "https://api.github.com/users/jorisvandenbossche/following{/other_user}",
      "gists_url": "https://api.github.com/users/jorisvandenbossche/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jorisvandenbossche/subscriptions",
      "organizations_url": "https://api.github.com/users/jorisvandenbossche/orgs",
      "repos_url": "https://api.github.com/users/jorisvandenbossche/repos",
      "events_url": "https://api.github.com/users/jorisvandenbossche/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jorisvandenbossche/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-04-09T14:32:47Z",
    "updated_at": "2014-04-09T14:33:07Z",
    "author_association": "MEMBER",
    "body": "Yes, indeed I reproduce the problem when closing and reopening the connection manually, so the data are indeed never written to the database on file. I think there is a `conn.commit()` (see https://docs.python.org/2/library/sqlite3.html) missing in the `insert` function in the legacy code (https://github.com/pydata/pandas/blob/master/pandas/io/sql.py#L779) \n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/39971610",
    "html_url": "https://github.com/pandas-dev/pandas/issues/6846#issuecomment-39971610",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/6846",
    "id": 39971610,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM5OTcxNjEw",
    "user": {
      "login": "jorisvandenbossche",
      "id": 1020496,
      "node_id": "MDQ6VXNlcjEwMjA0OTY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1020496?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jorisvandenbossche",
      "html_url": "https://github.com/jorisvandenbossche",
      "followers_url": "https://api.github.com/users/jorisvandenbossche/followers",
      "following_url": "https://api.github.com/users/jorisvandenbossche/following{/other_user}",
      "gists_url": "https://api.github.com/users/jorisvandenbossche/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jorisvandenbossche/subscriptions",
      "organizations_url": "https://api.github.com/users/jorisvandenbossche/orgs",
      "repos_url": "https://api.github.com/users/jorisvandenbossche/repos",
      "events_url": "https://api.github.com/users/jorisvandenbossche/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jorisvandenbossche/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-04-09T14:40:06Z",
    "updated_at": "2014-04-09T14:40:06Z",
    "author_association": "MEMBER",
    "body": "There was a `conn.commit()` in the previous version in 0.13.1 (https://github.com/pydata/pandas/blob/v0.13.1/pandas/io/sql.py#L240), so I think this is a regression.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/39976462",
    "html_url": "https://github.com/pandas-dev/pandas/issues/6846#issuecomment-39976462",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/6846",
    "id": 39976462,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM5OTc2NDYy",
    "user": {
      "login": "Acanthostega",
      "id": 4039200,
      "node_id": "MDQ6VXNlcjQwMzkyMDA=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/4039200?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Acanthostega",
      "html_url": "https://github.com/Acanthostega",
      "followers_url": "https://api.github.com/users/Acanthostega/followers",
      "following_url": "https://api.github.com/users/Acanthostega/following{/other_user}",
      "gists_url": "https://api.github.com/users/Acanthostega/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Acanthostega/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Acanthostega/subscriptions",
      "organizations_url": "https://api.github.com/users/Acanthostega/orgs",
      "repos_url": "https://api.github.com/users/Acanthostega/repos",
      "events_url": "https://api.github.com/users/Acanthostega/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Acanthostega/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-04-09T15:18:58Z",
    "updated_at": "2014-04-09T15:18:58Z",
    "author_association": "CONTRIBUTOR",
    "body": "@jorisvandenbossche I added a call to `commit()` in the `insert` method, and the problem seems to disappear. Do you want that I propose a patch or you think it's better if you do it yourself? I think that a test for the writing and reading in the SQL database with legacy should be added too, with the connection to the database closed before reading, to avoid any future regression. But I don't know sufficiently how pandas works in internal to propose one...\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/39982365",
    "html_url": "https://github.com/pandas-dev/pandas/issues/6846#issuecomment-39982365",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/6846",
    "id": 39982365,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM5OTgyMzY1",
    "user": {
      "login": "jorisvandenbossche",
      "id": 1020496,
      "node_id": "MDQ6VXNlcjEwMjA0OTY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1020496?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jorisvandenbossche",
      "html_url": "https://github.com/jorisvandenbossche",
      "followers_url": "https://api.github.com/users/jorisvandenbossche/followers",
      "following_url": "https://api.github.com/users/jorisvandenbossche/following{/other_user}",
      "gists_url": "https://api.github.com/users/jorisvandenbossche/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jorisvandenbossche/subscriptions",
      "organizations_url": "https://api.github.com/users/jorisvandenbossche/orgs",
      "repos_url": "https://api.github.com/users/jorisvandenbossche/repos",
      "events_url": "https://api.github.com/users/jorisvandenbossche/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jorisvandenbossche/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-04-09T16:04:55Z",
    "updated_at": "2014-04-09T16:05:35Z",
    "author_association": "MEMBER",
    "body": "@Acanthostega Good, if you want, certainly try to put up a PR! \nFor a test, that would certainly be good, I only don't know how to do this with sqlite, as we use a in-memory sqlite database in the tests, and I think this will lose all content when closing the connection? So we can't really test this bug that way.\nFor mysql we should certainly test it.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/40013799",
    "html_url": "https://github.com/pandas-dev/pandas/issues/6846#issuecomment-40013799",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/6846",
    "id": 40013799,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQwMDEzNzk5",
    "user": {
      "login": "Acanthostega",
      "id": 4039200,
      "node_id": "MDQ6VXNlcjQwMzkyMDA=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/4039200?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Acanthostega",
      "html_url": "https://github.com/Acanthostega",
      "followers_url": "https://api.github.com/users/Acanthostega/followers",
      "following_url": "https://api.github.com/users/Acanthostega/following{/other_user}",
      "gists_url": "https://api.github.com/users/Acanthostega/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Acanthostega/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Acanthostega/subscriptions",
      "organizations_url": "https://api.github.com/users/Acanthostega/orgs",
      "repos_url": "https://api.github.com/users/Acanthostega/repos",
      "events_url": "https://api.github.com/users/Acanthostega/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Acanthostega/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-04-09T20:42:15Z",
    "updated_at": "2014-04-09T20:42:15Z",
    "author_association": "CONTRIBUTOR",
    "body": "@jorisvandenbossche Ok! If I have enough time, I will try to do it this week end!\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/40014815",
    "html_url": "https://github.com/pandas-dev/pandas/issues/6846#issuecomment-40014815",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/6846",
    "id": 40014815,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQwMDE0ODE1",
    "user": {
      "login": "jorisvandenbossche",
      "id": 1020496,
      "node_id": "MDQ6VXNlcjEwMjA0OTY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1020496?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jorisvandenbossche",
      "html_url": "https://github.com/jorisvandenbossche",
      "followers_url": "https://api.github.com/users/jorisvandenbossche/followers",
      "following_url": "https://api.github.com/users/jorisvandenbossche/following{/other_user}",
      "gists_url": "https://api.github.com/users/jorisvandenbossche/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jorisvandenbossche/subscriptions",
      "organizations_url": "https://api.github.com/users/jorisvandenbossche/orgs",
      "repos_url": "https://api.github.com/users/jorisvandenbossche/repos",
      "events_url": "https://api.github.com/users/jorisvandenbossche/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jorisvandenbossche/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-04-09T20:51:46Z",
    "updated_at": "2014-04-09T20:51:46Z",
    "author_association": "MEMBER",
    "body": "@Acanthostega OK, let know how it goes! \n\nI updated the issue title/description to reflect the dicussion.\n"
  }
]
