[
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/4664596",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-4664596",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 4664596,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2NjQ1OTY=",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-03-23T17:58:37Z",
    "updated_at": "2012-03-23T17:58:37Z",
    "author_association": "MEMBER",
    "body": "Is this in the notebook or the Qt console?\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/4668861",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-4668861",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 4668861,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2Njg4NjE=",
    "user": {
      "login": "dfarmer",
      "id": 94208,
      "node_id": "MDQ6VXNlcjk0MjA4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/94208?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dfarmer",
      "html_url": "https://github.com/dfarmer",
      "followers_url": "https://api.github.com/users/dfarmer/followers",
      "following_url": "https://api.github.com/users/dfarmer/following{/other_user}",
      "gists_url": "https://api.github.com/users/dfarmer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dfarmer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dfarmer/subscriptions",
      "organizations_url": "https://api.github.com/users/dfarmer/orgs",
      "repos_url": "https://api.github.com/users/dfarmer/repos",
      "events_url": "https://api.github.com/users/dfarmer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dfarmer/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-03-23T22:05:53Z",
    "updated_at": "2012-03-23T22:05:53Z",
    "author_association": "NONE",
    "body": "Sorry I forgot to mention that. It's in Qt console.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/4669023",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-4669023",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 4669023,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2NjkwMjM=",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-03-23T22:20:28Z",
    "updated_at": "2012-03-23T22:20:28Z",
    "author_association": "MEMBER",
    "body": "I can't reproduce it with  pandas 0.7.2 and the development version of IPython, running on Ubuntu with PyQt4.\n\nPySide has given us some problems with tooltips before. Are you using PySide, and if so, what version?\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/4670058",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-4670058",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 4670058,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2NzAwNTg=",
    "user": {
      "login": "dfarmer",
      "id": 94208,
      "node_id": "MDQ6VXNlcjk0MjA4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/94208?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dfarmer",
      "html_url": "https://github.com/dfarmer",
      "followers_url": "https://api.github.com/users/dfarmer/followers",
      "following_url": "https://api.github.com/users/dfarmer/following{/other_user}",
      "gists_url": "https://api.github.com/users/dfarmer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dfarmer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dfarmer/subscriptions",
      "organizations_url": "https://api.github.com/users/dfarmer/orgs",
      "repos_url": "https://api.github.com/users/dfarmer/repos",
      "events_url": "https://api.github.com/users/dfarmer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dfarmer/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-03-23T23:47:06Z",
    "updated_at": "2012-03-23T23:47:06Z",
    "author_association": "NONE",
    "body": "I'm using PyQt4 4.8.6. I'm on windows 7 so building from source would be a bit painful, but I guess that's my only choice unless someone else can try to reproduce it on 0.12. For me it's 100% reproducible (I've done it 5 times now). \n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/4670203",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-4670203",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 4670203,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2NzAyMDM=",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-03-24T00:04:15Z",
    "updated_at": "2012-03-24T00:04:15Z",
    "author_association": "MEMBER",
    "body": "Running IPython from source shouldn't be too hard - there's nothing to compile, just grab the latest version ([zipball here](https://github.com/ipython/ipython/zipball/master) if you don't have git installed), and run `python setup.py install`.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/4670432",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-4670432",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 4670432,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2NzA0MzI=",
    "user": {
      "login": "fperez",
      "id": 57394,
      "node_id": "MDQ6VXNlcjU3Mzk0",
      "avatar_url": "https://avatars1.githubusercontent.com/u/57394?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fperez",
      "html_url": "https://github.com/fperez",
      "followers_url": "https://api.github.com/users/fperez/followers",
      "following_url": "https://api.github.com/users/fperez/following{/other_user}",
      "gists_url": "https://api.github.com/users/fperez/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fperez/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fperez/subscriptions",
      "organizations_url": "https://api.github.com/users/fperez/orgs",
      "repos_url": "https://api.github.com/users/fperez/repos",
      "events_url": "https://api.github.com/users/fperez/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fperez/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-03-24T00:32:28Z",
    "updated_at": "2012-03-24T00:32:28Z",
    "author_association": "MEMBER",
    "body": "Well, it would be easier to test with IPython git master, that doesn't require that you build anything from source.  Because it looks like this problem, whatever it is underneath, is already fixed in git master.  There's no point in us confirming that there was a bug in 0.12 if it's already been fixed in the current master.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/4676016",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-4676016",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 4676016,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2NzYwMTY=",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-03-24T19:42:03Z",
    "updated_at": "2012-03-24T19:42:03Z",
    "author_association": "MEMBER",
    "body": "Clarification question: is it the _kernel_ that is dying, or the frontend?  If the kernel dies, the frontend simply shows a message 'kernel appears to have died...'.  I expect this is the frontend, and a Qt/PyQt bug (as we have seen with PySide on OSX in the past).\n\nAssuming this is a similar issue, the workaround is to use `IPythonWidget.enable_calltips=False` to just disable these calltips altogether.\n\nAlso, re: installing current dev IPython, it can actually be a one-liner:\n\n```\n$> easy_install https://github.com/ipython/ipython/zipball/master\n```\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/4679400",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-4679400",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 4679400,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2Nzk0MDA=",
    "user": {
      "login": "dfarmer",
      "id": 94208,
      "node_id": "MDQ6VXNlcjk0MjA4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/94208?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dfarmer",
      "html_url": "https://github.com/dfarmer",
      "followers_url": "https://api.github.com/users/dfarmer/followers",
      "following_url": "https://api.github.com/users/dfarmer/following{/other_user}",
      "gists_url": "https://api.github.com/users/dfarmer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dfarmer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dfarmer/subscriptions",
      "organizations_url": "https://api.github.com/users/dfarmer/orgs",
      "repos_url": "https://api.github.com/users/dfarmer/repos",
      "events_url": "https://api.github.com/users/dfarmer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dfarmer/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-03-25T04:28:29Z",
    "updated_at": "2012-03-25T04:35:57Z",
    "author_association": "NONE",
    "body": "@minrk It's the kernel, I am getting the \"Lost kernel heartbeat, try to reconnect?\" dialog. I just updated to 0.13.dev using your instructions and I am able to reproduce the problem (and this is on a 2nd machine. My initial report was about my desktop at work, this is on my home laptop). \n\nInterestingly, the problem did not occur in IPython 0.12 with Pandas 0.7.0, but once I updated pandas and IPython I now get this behavior on my laptop as well. At work I have only PyQt4, and at home I have only PySide installed so that doesn't appear to correlate. \n\nDisabling calltips does work around the issue. Is there anything I can do to help figure out what exactly is triggering this?\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/4687404",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-4687404",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 4687404,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2ODc0MDQ=",
    "user": {
      "login": "fperez",
      "id": 57394,
      "node_id": "MDQ6VXNlcjU3Mzk0",
      "avatar_url": "https://avatars1.githubusercontent.com/u/57394?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fperez",
      "html_url": "https://github.com/fperez",
      "followers_url": "https://api.github.com/users/fperez/followers",
      "following_url": "https://api.github.com/users/fperez/following{/other_user}",
      "gists_url": "https://api.github.com/users/fperez/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fperez/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fperez/subscriptions",
      "organizations_url": "https://api.github.com/users/fperez/orgs",
      "repos_url": "https://api.github.com/users/fperez/repos",
      "events_url": "https://api.github.com/users/fperez/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fperez/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-03-26T03:27:29Z",
    "updated_at": "2012-03-26T03:27:29Z",
    "author_association": "MEMBER",
    "body": "From your description, it sounds like pandas is segfaulting when introspected.  If that's the case, there's really nothing we could do from IPython, as the bug needs to be fixed in pandas itself.  We can (and do) catch exceptions when introspecting objects, but if an object has a bug that causes python itself to segfault, there's nothing we can do to stop that from occurring.  As indicated, you can disable calltips if you want.\n\nI'm pinging her @wesm to see if he has seen the problem in pandas already... He may have valuable info to contribute here.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/4792890",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-4792890",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 4792890,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3OTI4OTA=",
    "user": {
      "login": "wesm",
      "id": 329591,
      "node_id": "MDQ6VXNlcjMyOTU5MQ==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/329591?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wesm",
      "html_url": "https://github.com/wesm",
      "followers_url": "https://api.github.com/users/wesm/followers",
      "following_url": "https://api.github.com/users/wesm/following{/other_user}",
      "gists_url": "https://api.github.com/users/wesm/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wesm/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wesm/subscriptions",
      "organizations_url": "https://api.github.com/users/wesm/orgs",
      "repos_url": "https://api.github.com/users/wesm/repos",
      "events_url": "https://api.github.com/users/wesm/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wesm/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-03-28T22:22:33Z",
    "updated_at": "2012-03-29T04:45:09Z",
    "author_association": "NONE",
    "body": "I honestly don't know why or how pandas could be segfaulting on something like that. I'd have to duplicate the environment on my Windows VM at work to really test (not an issue with 0.7.2 + IPython git master on Ubuntu). Maybe sometime in the next couple weeks\n\n@dfarmer any way that you can use [git bisect](http://book.git-scm.com/5_finding_issues_-_git_bisect.html) to determine the commit that causes the crash to start happening between 0.7.0 and 0.7.2? This might be hard as you may not have the right C compiler stuff setup on your Windows machine\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/4793062",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-4793062",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 4793062,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3OTMwNjI=",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-03-28T22:33:36Z",
    "updated_at": "2012-03-28T22:33:36Z",
    "author_association": "MEMBER",
    "body": "I wonder if it's some unicode bug, possibly that we've already fixed since 0.12. That might explain why it's only manifesting on Windows. Can you try running `ipython qtconsole` at a terminal, and see if there's any error message when it hits the problem?\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/4796806",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-4796806",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 4796806,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3OTY4MDY=",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-03-29T04:46:44Z",
    "updated_at": "2012-03-29T05:02:09Z",
    "author_association": "MEMBER",
    "body": "Definitely run in a terminal, and probably add `--debug`, so you might get some extra pertinent info.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/5020324",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-5020324",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 5020324,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwMjAzMjQ=",
    "user": {
      "login": "wesm",
      "id": 329591,
      "node_id": "MDQ6VXNlcjMyOTU5MQ==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/329591?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wesm",
      "html_url": "https://github.com/wesm",
      "followers_url": "https://api.github.com/users/wesm/followers",
      "following_url": "https://api.github.com/users/wesm/following{/other_user}",
      "gists_url": "https://api.github.com/users/wesm/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wesm/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wesm/subscriptions",
      "organizations_url": "https://api.github.com/users/wesm/orgs",
      "repos_url": "https://api.github.com/users/wesm/repos",
      "events_url": "https://api.github.com/users/wesm/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wesm/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-04-09T02:37:21Z",
    "updated_at": "2012-04-09T02:37:21Z",
    "author_association": "NONE",
    "body": "@dfarmer let me know if you get any more information on this per the other guys' suggestions\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/5031108",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-5031108",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 5031108,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUwMzExMDg=",
    "user": {
      "login": "dfarmer",
      "id": 94208,
      "node_id": "MDQ6VXNlcjk0MjA4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/94208?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dfarmer",
      "html_url": "https://github.com/dfarmer",
      "followers_url": "https://api.github.com/users/dfarmer/followers",
      "following_url": "https://api.github.com/users/dfarmer/following{/other_user}",
      "gists_url": "https://api.github.com/users/dfarmer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dfarmer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dfarmer/subscriptions",
      "organizations_url": "https://api.github.com/users/dfarmer/orgs",
      "repos_url": "https://api.github.com/users/dfarmer/repos",
      "events_url": "https://api.github.com/users/dfarmer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dfarmer/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-04-09T18:52:29Z",
    "updated_at": "2012-04-09T18:52:29Z",
    "author_association": "NONE",
    "body": "Sorry for the radio silence, I've been swamped lately. I'll try some of these suggestions and get back to you guys. Thanks for looking at it.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/5293868",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-5293868",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 5293868,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUyOTM4Njg=",
    "user": {
      "login": "dfarmer",
      "id": 94208,
      "node_id": "MDQ6VXNlcjk0MjA4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/94208?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dfarmer",
      "html_url": "https://github.com/dfarmer",
      "followers_url": "https://api.github.com/users/dfarmer/followers",
      "following_url": "https://api.github.com/users/dfarmer/following{/other_user}",
      "gists_url": "https://api.github.com/users/dfarmer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dfarmer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dfarmer/subscriptions",
      "organizations_url": "https://api.github.com/users/dfarmer/orgs",
      "repos_url": "https://api.github.com/users/dfarmer/repos",
      "events_url": "https://api.github.com/users/dfarmer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dfarmer/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-04-23T22:49:35Z",
    "updated_at": "2012-04-23T22:49:35Z",
    "author_association": "NONE",
    "body": "Sorry again for the long delay, as it happens today I got a traceback when this happened. Not sure why. Here's what I got:\n\n```\n\nindice.reindex_axs\nreindex  reindex_axis  reindex_Error in sys.excepthook:\nTraceback (most recent call last):\n  File \"C:\\Python27\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1033, in __call__\n    self.handler((etype, evalue, etb))\n  File \"C:\\Python27\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1022, in handler\n    ostream.write(self.text(etype, evalue, etb))\nIOError: [Errno 22] Invalid argument\n\nOriginal exception was:\nTraceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"C:\\Python27\\lib\\site-packages\\IPython\\zmq\\ipkernel.py\", line 647, in main\n    app.start()\n  File \"C:\\Python27\\lib\\site-packages\\IPython\\zmq\\kernelapp.py\", line 300, in start\n    self.kernel.start()\n  File \"C:\\Python27\\lib\\site-packages\\IPython\\zmq\\ipkernel.py\", line 192, in start\n    self.do_one_iteration()\n  File \"C:\\Python27\\lib\\site-packages\\IPython\\zmq\\ipkernel.py\", line 159, in do_one_iteration\n    handler(ident, msg)\n  File \"C:\\Python27\\lib\\site-packages\\IPython\\zmq\\ipkernel.py\", line 366, in object_info_request\n    oinfo, parent, ident)\n  File \"C:\\Python27\\lib\\site-packages\\IPython\\zmq\\session.py\", line 558, in send\n    to_send = self.serialize(msg, ident)\n  File \"C:\\Python27\\lib\\site-packages\\IPython\\zmq\\session.py\", line 462, in serialize\n    content = self.pack(content)\n  File \"C:\\Python27\\lib\\site-packages\\IPython\\zmq\\session.py\", line 77, in <lambda>\n    json_packer = lambda obj: jsonapi.dumps(obj, **{key:date_default})\n  File \"C:\\Python27\\lib\\site-packages\\zmq\\utils\\jsonapi.py\", line 67, in jsonlib_dumps\n    return _squash_unicode(jsonmod.dumps(o,**kwargs))\n  File \"C:\\Python27\\lib\\site-packages\\jsonlib.py\", line 803, in write\n    UserString, Decimal)\n  File \"C:\\Python27\\lib\\site-packages\\jsonlib.py\", line 481, in no_nan\n    raise WriteError (\"Cannot serialize NaN.\n```\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/5294060",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-5294060",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 5294060,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUyOTQwNjA=",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-04-23T23:03:23Z",
    "updated_at": "2012-04-23T23:03:23Z",
    "author_association": "MEMBER",
    "body": "Aha! jsonlib strikes again.  If you do any of:\n\na) remove jsonlib\nb) install jsonlib2\nc) use pyzmq from git master (2.2.0 release soon, which removes support for jsonlib)\n\nyou should be set.  I will do a PR shortly that ensures jsonlib is never used in IPython, because it's never caused anything but trouble.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/5294865",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-5294865",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 5294865,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUyOTQ4NjU=",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-04-24T00:06:17Z",
    "updated_at": "2012-04-24T00:06:17Z",
    "author_association": "MEMBER",
    "body": "So, this is _really_ a jsonlib bug, but IPython/pyzmq's bug is that jsonlib was ever supported at all. pyzmq-2.2.0 will remedy this, and PR #1652 does the same for IPython with older pyzmq.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/5298074",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-5298074",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 5298074,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUyOTgwNzQ=",
    "user": {
      "login": "fperez",
      "id": 57394,
      "node_id": "MDQ6VXNlcjU3Mzk0",
      "avatar_url": "https://avatars1.githubusercontent.com/u/57394?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fperez",
      "html_url": "https://github.com/fperez",
      "followers_url": "https://api.github.com/users/fperez/followers",
      "following_url": "https://api.github.com/users/fperez/following{/other_user}",
      "gists_url": "https://api.github.com/users/fperez/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fperez/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fperez/subscriptions",
      "organizations_url": "https://api.github.com/users/fperez/orgs",
      "repos_url": "https://api.github.com/users/fperez/repos",
      "events_url": "https://api.github.com/users/fperez/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fperez/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-04-24T06:00:00Z",
    "updated_at": "2012-04-24T06:00:00Z",
    "author_association": "MEMBER",
    "body": "Thanks @minrk for the quick cleanup!  I've merged it now; @dfarmer: please let us know if you can still see the problem after updating to git master and we'll reopen the issue if necessary.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/5307392",
    "html_url": "https://github.com/ipython/ipython/issues/1520#issuecomment-5307392",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1520",
    "id": 5307392,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUzMDczOTI=",
    "user": {
      "login": "dfarmer",
      "id": 94208,
      "node_id": "MDQ6VXNlcjk0MjA4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/94208?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dfarmer",
      "html_url": "https://github.com/dfarmer",
      "followers_url": "https://api.github.com/users/dfarmer/followers",
      "following_url": "https://api.github.com/users/dfarmer/following{/other_user}",
      "gists_url": "https://api.github.com/users/dfarmer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dfarmer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dfarmer/subscriptions",
      "organizations_url": "https://api.github.com/users/dfarmer/orgs",
      "repos_url": "https://api.github.com/users/dfarmer/repos",
      "events_url": "https://api.github.com/users/dfarmer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dfarmer/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-04-24T15:37:57Z",
    "updated_at": "2012-04-24T15:37:57Z",
    "author_association": "NONE",
    "body": "I updated to master and it looks good. Thanks guys!\n"
  }
]
