[
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/12461660",
    "html_url": "https://github.com/ipython/ipython/issues/2209#issuecomment-12461660",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2209",
    "id": 12461660,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyNDYxNjYw",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-01-19T21:40:19Z",
    "updated_at": "2013-01-19T21:40:19Z",
    "author_association": "MEMBER",
    "body": "Do you see any log messages in the server's console window?\n\nI bet there's an encoding or permissions issue happening.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/22565956",
    "html_url": "https://github.com/ipython/ipython/issues/2209#issuecomment-22565956",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2209",
    "id": 22565956,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyNTY1OTU2",
    "user": {
      "login": "badbitstuff",
      "id": 5221644,
      "node_id": "MDQ6VXNlcjUyMjE2NDQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/5221644?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/badbitstuff",
      "html_url": "https://github.com/badbitstuff",
      "followers_url": "https://api.github.com/users/badbitstuff/followers",
      "following_url": "https://api.github.com/users/badbitstuff/following{/other_user}",
      "gists_url": "https://api.github.com/users/badbitstuff/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/badbitstuff/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/badbitstuff/subscriptions",
      "organizations_url": "https://api.github.com/users/badbitstuff/orgs",
      "repos_url": "https://api.github.com/users/badbitstuff/repos",
      "events_url": "https://api.github.com/users/badbitstuff/events{/privacy}",
      "received_events_url": "https://api.github.com/users/badbitstuff/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-08-13T13:50:56Z",
    "updated_at": "2013-08-15T05:58:05Z",
    "author_association": "NONE",
    "body": "Same problem here, with ipython 1.0. Tested on 32 bits installations on both windows vista 32bit and windows 7 64 bit. Installed manually and with easy_install -U ipython[all]. Downgraded tornado to 2.1 as well.  Same notebook works perfectly on linux. \n\nStarted the nb server with\nipython notebook --pylab inline --debug --no-browser\n\nThe nb saves successfully after one plot with one line and is more likely not savable when plotting more figures/lines.\n\nPlotting the following in two figures, will certainly make the nb unresponsive:\n\n```\nplot(randn(100).reshape((10,10)))\n```\n\nThere is no log messages when trying to save, except for \"polling kernel ...\". \nSame problem when running as administrator and/or disabling uac. Not certain how this can be an encoding problem.\n\nAdded some print statements in nbmanager.py, method save_notebook,  line 156 and html/services/notebooks/handlers.py method put line 76 , none of these methods are entered when saving fails.\n\nThis seems to be the same problem as posted here:\nhttp://mail.scipy.org/pipermail/ipython-dev/2012-August/010132.html\n\nUpdate: none of the above mentioned methods are entered ...\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/22589719",
    "html_url": "https://github.com/ipython/ipython/issues/2209#issuecomment-22589719",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2209",
    "id": 22589719,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyNTg5NzE5",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-08-13T19:13:39Z",
    "updated_at": "2013-08-13T19:13:44Z",
    "author_association": "MEMBER",
    "body": "any messages in the js console?\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/22618132",
    "html_url": "https://github.com/ipython/ipython/issues/2209#issuecomment-22618132",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2209",
    "id": 22618132,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyNjE4MTMy",
    "user": {
      "login": "badbitstuff",
      "id": 5221644,
      "node_id": "MDQ6VXNlcjUyMjE2NDQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/5221644?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/badbitstuff",
      "html_url": "https://github.com/badbitstuff",
      "followers_url": "https://api.github.com/users/badbitstuff/followers",
      "following_url": "https://api.github.com/users/badbitstuff/following{/other_user}",
      "gists_url": "https://api.github.com/users/badbitstuff/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/badbitstuff/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/badbitstuff/subscriptions",
      "organizations_url": "https://api.github.com/users/badbitstuff/orgs",
      "repos_url": "https://api.github.com/users/badbitstuff/repos",
      "events_url": "https://api.github.com/users/badbitstuff/events{/privacy}",
      "received_events_url": "https://api.github.com/users/badbitstuff/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-08-14T06:56:21Z",
    "updated_at": "2013-08-14T06:56:21Z",
    "author_association": "NONE",
    "body": "Using chrome 28.0.1500.95 m\n\nNothing after initialization from the js console\n\n```\nDefault extension for metadata editing loaded. default.js:88\nSlideshow extension for metadata editing loaded. slideshow.js:56\npatching CM for undefined indent main.js:27\nKernel started:  778f0420-0fc6-4a50-aef0-8151a2f3be08 kernel.js:110\nStarting WebSockets: ws://127.0.0.1:8888/kernels/778f0420-0fc6-4a50-aef0-8151a2f3be08 kernel.js:143\n```\n\nAfter pressing Save and Checkpoint about 10 times, the notebook succeeded to save once. A failing save gives the following network activity:\n\n```\nPUT http://127.0.0.1:8888/notebooks/1bdbe196-041b-453e-900d-fce5cc947c27 HTTP/1.1\nAccept: */*\nReferer: http://127.0.0.1:8888/1bdbe196-041b-453e-900d-fce5cc947c27\nOrigin: http://127.0.0.1:8888\nX-Requested-With: XMLHttpRequest\nUser-Agent: Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.95 Safari/537.36\nContent-Type: application/json\n```\n\nWith the following response header:\n\n```\nHTTP/1.1 0 \n```\n\nThe successful request:\n\n```\nPUT /notebooks/1bdbe196-041b-453e-900d-fce5cc947c27 HTTP/1.1\nHost: 127.0.0.1:8888\nConnection: keep-alive\nContent-Length: 57225\nAccept: */*\nOrigin: http://127.0.0.1:8888\nX-Requested-With: XMLHttpRequest\nUser-Agent: Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.95 Safari/537.36\nContent-Type: application/json\nReferer: http://127.0.0.1:8888/1bdbe196-041b-453e-900d-fce5cc947c27\nAccept-Encoding: gzip,deflate,sdch\nAccept-Language: en-US,en;q=0.8\n```\n\nWith the following response header:\n\n```\nHTTP/1.1 204 No Content\nDate: Wed, 14 Aug 2013 06:46:50 GMT\nContent-Length: 0\nContent-Type: text/html; charset=UTF-8\nServer: TornadoServer/3.1\nSet-Cookie: username-127.0.0.1-8888=; expires=Tue, 14 Aug 2012 06:46:50 GMT; Path=/\n```\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/46267046",
    "html_url": "https://github.com/ipython/ipython/issues/2209#issuecomment-46267046",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2209",
    "id": 46267046,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2MjY3MDQ2",
    "user": {
      "login": "ivanov",
      "id": 118211,
      "node_id": "MDQ6VXNlcjExODIxMQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/118211?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivanov",
      "html_url": "https://github.com/ivanov",
      "followers_url": "https://api.github.com/users/ivanov/followers",
      "following_url": "https://api.github.com/users/ivanov/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivanov/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivanov/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivanov/subscriptions",
      "organizations_url": "https://api.github.com/users/ivanov/orgs",
      "repos_url": "https://api.github.com/users/ivanov/repos",
      "events_url": "https://api.github.com/users/ivanov/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivanov/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-06-17T04:51:57Z",
    "updated_at": "2014-06-17T04:51:57Z",
    "author_association": "MEMBER",
    "body": "@knorthover @badbitstuff are either of you still seeing this behavior on the latest version of IPython? if not, I'll go ahead and close this\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/46267779",
    "html_url": "https://github.com/ipython/ipython/issues/2209#issuecomment-46267779",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2209",
    "id": 46267779,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2MjY3Nzc5",
    "user": {
      "login": "ivanov",
      "id": 118211,
      "node_id": "MDQ6VXNlcjExODIxMQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/118211?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivanov",
      "html_url": "https://github.com/ivanov",
      "followers_url": "https://api.github.com/users/ivanov/followers",
      "following_url": "https://api.github.com/users/ivanov/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivanov/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivanov/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivanov/subscriptions",
      "organizations_url": "https://api.github.com/users/ivanov/orgs",
      "repos_url": "https://api.github.com/users/ivanov/repos",
      "events_url": "https://api.github.com/users/ivanov/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivanov/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-06-17T05:08:23Z",
    "updated_at": "2014-06-17T05:08:23Z",
    "author_association": "MEMBER",
    "body": "Marking as needs-info so on a future pass (in a month?) we can close this if there's no activity\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/46293616",
    "html_url": "https://github.com/ipython/ipython/issues/2209#issuecomment-46293616",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2209",
    "id": 46293616,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2MjkzNjE2",
    "user": {
      "login": "badbitstuff",
      "id": 5221644,
      "node_id": "MDQ6VXNlcjUyMjE2NDQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/5221644?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/badbitstuff",
      "html_url": "https://github.com/badbitstuff",
      "followers_url": "https://api.github.com/users/badbitstuff/followers",
      "following_url": "https://api.github.com/users/badbitstuff/following{/other_user}",
      "gists_url": "https://api.github.com/users/badbitstuff/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/badbitstuff/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/badbitstuff/subscriptions",
      "organizations_url": "https://api.github.com/users/badbitstuff/orgs",
      "repos_url": "https://api.github.com/users/badbitstuff/repos",
      "events_url": "https://api.github.com/users/badbitstuff/events{/privacy}",
      "received_events_url": "https://api.github.com/users/badbitstuff/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-06-17T11:06:36Z",
    "updated_at": "2014-06-17T11:06:36Z",
    "author_association": "NONE",
    "body": "@ivanov, installed anaconda after a while, no problems since. Either anaconda fixed the prerequisites  or a newer version did the trick. \n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/46334058",
    "html_url": "https://github.com/ipython/ipython/issues/2209#issuecomment-46334058",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2209",
    "id": 46334058,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2MzM0MDU4",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-06-17T16:50:49Z",
    "updated_at": "2014-06-17T16:50:49Z",
    "author_association": "MEMBER",
    "body": "OK, let's close this, then. We can always reopen it if someone else can replicate the symptoms.\n"
  }
]
