[
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/75392770",
    "html_url": "https://github.com/ipython/ipython/issues/7829#issuecomment-75392770",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/7829",
    "id": 75392770,
    "node_id": "MDEyOklzc3VlQ29tbWVudDc1MzkyNzcw",
    "user": {
      "login": "damianavila",
      "id": 1640669,
      "node_id": "MDQ6VXNlcjE2NDA2Njk=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1640669?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/damianavila",
      "html_url": "https://github.com/damianavila",
      "followers_url": "https://api.github.com/users/damianavila/followers",
      "following_url": "https://api.github.com/users/damianavila/following{/other_user}",
      "gists_url": "https://api.github.com/users/damianavila/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/damianavila/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/damianavila/subscriptions",
      "organizations_url": "https://api.github.com/users/damianavila/orgs",
      "repos_url": "https://api.github.com/users/damianavila/repos",
      "events_url": "https://api.github.com/users/damianavila/events{/privacy}",
      "received_events_url": "https://api.github.com/users/damianavila/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-02-21T21:03:15Z",
    "updated_at": "2015-02-21T21:50:51Z",
    "author_association": "MEMBER",
    "body": "Can you test if \n\n~~ipython nbconvert your_slides.ipynb --to slides --post serve --reveal-prefix~~\n\nis working for you? I am suspecting on a failure in the redirection...\n\nEDIT: this is the correct command:\n\n`ipython nbconvert your_slides.ipynb --to slides --post serve --ServePostProcessor.reveal_cdn=\"http://cdn.jsdelivr.net/reveal.js/2.5.0\"`\n\n(everything in one line).\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/75395571",
    "html_url": "https://github.com/ipython/ipython/issues/7829#issuecomment-75395571",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/7829",
    "id": 75395571,
    "node_id": "MDEyOklzc3VlQ29tbWVudDc1Mzk1NTcx",
    "user": {
      "login": "damianavila",
      "id": 1640669,
      "node_id": "MDQ6VXNlcjE2NDA2Njk=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1640669?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/damianavila",
      "html_url": "https://github.com/damianavila",
      "followers_url": "https://api.github.com/users/damianavila/followers",
      "following_url": "https://api.github.com/users/damianavila/following{/other_user}",
      "gists_url": "https://api.github.com/users/damianavila/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/damianavila/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/damianavila/subscriptions",
      "organizations_url": "https://api.github.com/users/damianavila/orgs",
      "repos_url": "https://api.github.com/users/damianavila/repos",
      "events_url": "https://api.github.com/users/damianavila/events{/privacy}",
      "received_events_url": "https://api.github.com/users/damianavila/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-02-21T22:05:48Z",
    "updated_at": "2015-02-21T22:05:48Z",
    "author_association": "MEMBER",
    "body": "ok... I think I know what the problem is... when we use `http://` the thing is working but not when you use the secured one, I mean `https://`...\n@minrk @rgbkrk is there something we can do the the ServePostProcessor implementation to accept secure http?\nAs a quick workaround we can change the default url to `http` if necessary...\nBTW, this probably need to be inside 3.0, if not the `--post serve` option is not working by default.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/75418641",
    "html_url": "https://github.com/ipython/ipython/issues/7829#issuecomment-75418641",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/7829",
    "id": 75418641,
    "node_id": "MDEyOklzc3VlQ29tbWVudDc1NDE4NjQx",
    "user": {
      "login": "lmarti",
      "id": 1521337,
      "node_id": "MDQ6VXNlcjE1MjEzMzc=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1521337?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lmarti",
      "html_url": "https://github.com/lmarti",
      "followers_url": "https://api.github.com/users/lmarti/followers",
      "following_url": "https://api.github.com/users/lmarti/following{/other_user}",
      "gists_url": "https://api.github.com/users/lmarti/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lmarti/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lmarti/subscriptions",
      "organizations_url": "https://api.github.com/users/lmarti/orgs",
      "repos_url": "https://api.github.com/users/lmarti/repos",
      "events_url": "https://api.github.com/users/lmarti/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lmarti/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-02-22T04:09:05Z",
    "updated_at": "2015-02-22T04:12:21Z",
    "author_association": "NONE",
    "body": "The command you suggested works for me.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/75676010",
    "html_url": "https://github.com/ipython/ipython/issues/7829#issuecomment-75676010",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/7829",
    "id": 75676010,
    "node_id": "MDEyOklzc3VlQ29tbWVudDc1Njc2MDEw",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-02-24T00:49:23Z",
    "updated_at": "2015-02-24T00:49:23Z",
    "author_association": "MEMBER",
    "body": "This appears to be working for me with the https URL we use by default in master. Why would redirecting to an https URL be a problem?\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/75800660",
    "html_url": "https://github.com/ipython/ipython/issues/7829#issuecomment-75800660",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/7829",
    "id": 75800660,
    "node_id": "MDEyOklzc3VlQ29tbWVudDc1ODAwNjYw",
    "user": {
      "login": "damianavila",
      "id": 1640669,
      "node_id": "MDQ6VXNlcjE2NDA2Njk=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1640669?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/damianavila",
      "html_url": "https://github.com/damianavila",
      "followers_url": "https://api.github.com/users/damianavila/followers",
      "following_url": "https://api.github.com/users/damianavila/following{/other_user}",
      "gists_url": "https://api.github.com/users/damianavila/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/damianavila/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/damianavila/subscriptions",
      "organizations_url": "https://api.github.com/users/damianavila/orgs",
      "repos_url": "https://api.github.com/users/damianavila/repos",
      "events_url": "https://api.github.com/users/damianavila/events{/privacy}",
      "received_events_url": "https://api.github.com/users/damianavila/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-02-24T17:19:39Z",
    "updated_at": "2015-02-24T17:19:39Z",
    "author_association": "MEMBER",
    "body": "This was not working the other day, let me check again... maybe a `jsdeliv` issue?\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/75803140",
    "html_url": "https://github.com/ipython/ipython/issues/7829#issuecomment-75803140",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/7829",
    "id": 75803140,
    "node_id": "MDEyOklzc3VlQ29tbWVudDc1ODAzMTQw",
    "user": {
      "login": "lmarti",
      "id": 1521337,
      "node_id": "MDQ6VXNlcjE1MjEzMzc=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1521337?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lmarti",
      "html_url": "https://github.com/lmarti",
      "followers_url": "https://api.github.com/users/lmarti/followers",
      "following_url": "https://api.github.com/users/lmarti/following{/other_user}",
      "gists_url": "https://api.github.com/users/lmarti/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lmarti/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lmarti/subscriptions",
      "organizations_url": "https://api.github.com/users/lmarti/orgs",
      "repos_url": "https://api.github.com/users/lmarti/repos",
      "events_url": "https://api.github.com/users/lmarti/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lmarti/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-02-24T17:31:50Z",
    "updated_at": "2015-02-24T17:31:50Z",
    "author_association": "NONE",
    "body": "The situation is the same on my side.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/75807034",
    "html_url": "https://github.com/ipython/ipython/issues/7829#issuecomment-75807034",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/7829",
    "id": 75807034,
    "node_id": "MDEyOklzc3VlQ29tbWVudDc1ODA3MDM0",
    "user": {
      "login": "damianavila",
      "id": 1640669,
      "node_id": "MDQ6VXNlcjE2NDA2Njk=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1640669?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/damianavila",
      "html_url": "https://github.com/damianavila",
      "followers_url": "https://api.github.com/users/damianavila/followers",
      "following_url": "https://api.github.com/users/damianavila/following{/other_user}",
      "gists_url": "https://api.github.com/users/damianavila/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/damianavila/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/damianavila/subscriptions",
      "organizations_url": "https://api.github.com/users/damianavila/orgs",
      "repos_url": "https://api.github.com/users/damianavila/repos",
      "events_url": "https://api.github.com/users/damianavila/events{/privacy}",
      "received_events_url": "https://api.github.com/users/damianavila/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-02-24T17:44:47Z",
    "updated_at": "2015-02-24T17:44:47Z",
    "author_association": "MEMBER",
    "body": "OK, this is not working for me in master... I have this in the JS console:\n\n```\n Resource interpreted as Stylesheet but transferred with MIME type text/html: \"http://127.0.0.1:8000/reveal.js/css/reveal.css\".\ntest_slides.slides.html:19 Resource interpreted as Stylesheet but transferred with MIME type text/html: \"http://127.0.0.1:8000/reveal.js/css/theme/simple.css\".\ntest_slides.slides.html:13675 Resource interpreted as Script but transferred with MIME type text/html: \"http://127.0.0.1:8000/reveal.js/lib/js/head.min.js\".\ntest_slides.slides.html:13677 Resource interpreted as Script but transferred with MIME type text/html: \"http://127.0.0.1:8000/reveal.js/js/reveal.js\".\ntest_slides.slides.html:13682 Uncaught ReferenceError: Reveal is not defined\ntest_slides.slides.html:13722 Uncaught ReferenceError: Reveal is not defined\n```\n\nThe funny thing is that downgrading tornado to 3.2, I can get it working...\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/75811144",
    "html_url": "https://github.com/ipython/ipython/issues/7829#issuecomment-75811144",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/7829",
    "id": 75811144,
    "node_id": "MDEyOklzc3VlQ29tbWVudDc1ODExMTQ0",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-02-24T18:05:34Z",
    "updated_at": "2015-02-24T18:05:34Z",
    "author_association": "MEMBER",
    "body": "I know what the issue is, I'll have a PR with some fixes shortly. The proxy request is failing due to a missing package, and we are ignoring the error.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/75841101",
    "html_url": "https://github.com/ipython/ipython/issues/7829#issuecomment-75841101",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/7829",
    "id": 75841101,
    "node_id": "MDEyOklzc3VlQ29tbWVudDc1ODQxMTAx",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-02-24T20:41:01Z",
    "updated_at": "2015-02-24T20:41:01Z",
    "author_association": "MEMBER",
    "body": "#7850 \n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/86774042",
    "html_url": "https://github.com/ipython/ipython/issues/7829#issuecomment-86774042",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/7829",
    "id": 86774042,
    "node_id": "MDEyOklzc3VlQ29tbWVudDg2Nzc0MDQy",
    "user": {
      "login": "hsgPU",
      "id": 11668004,
      "node_id": "MDQ6VXNlcjExNjY4MDA0",
      "avatar_url": "https://avatars3.githubusercontent.com/u/11668004?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/hsgPU",
      "html_url": "https://github.com/hsgPU",
      "followers_url": "https://api.github.com/users/hsgPU/followers",
      "following_url": "https://api.github.com/users/hsgPU/following{/other_user}",
      "gists_url": "https://api.github.com/users/hsgPU/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/hsgPU/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/hsgPU/subscriptions",
      "organizations_url": "https://api.github.com/users/hsgPU/orgs",
      "repos_url": "https://api.github.com/users/hsgPU/repos",
      "events_url": "https://api.github.com/users/hsgPU/events{/privacy}",
      "received_events_url": "https://api.github.com/users/hsgPU/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-03-27T00:44:52Z",
    "updated_at": "2015-03-27T00:44:52Z",
    "author_association": "NONE",
    "body": "I was having a huge amount of trouble in dealing with this, but thankfully the Feb 21 comment worked finely for me... Honestly, I don't believe this bug is fixed. ;D\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/87068490",
    "html_url": "https://github.com/ipython/ipython/issues/7829#issuecomment-87068490",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/7829",
    "id": 87068490,
    "node_id": "MDEyOklzc3VlQ29tbWVudDg3MDY4NDkw",
    "user": {
      "login": "damianavila",
      "id": 1640669,
      "node_id": "MDQ6VXNlcjE2NDA2Njk=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1640669?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/damianavila",
      "html_url": "https://github.com/damianavila",
      "followers_url": "https://api.github.com/users/damianavila/followers",
      "following_url": "https://api.github.com/users/damianavila/following{/other_user}",
      "gists_url": "https://api.github.com/users/damianavila/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/damianavila/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/damianavila/subscriptions",
      "organizations_url": "https://api.github.com/users/damianavila/orgs",
      "repos_url": "https://api.github.com/users/damianavila/repos",
      "events_url": "https://api.github.com/users/damianavila/events{/privacy}",
      "received_events_url": "https://api.github.com/users/damianavila/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-03-27T19:43:35Z",
    "updated_at": "2015-03-27T19:43:35Z",
    "author_association": "MEMBER",
    "body": "AFAIK, the `certifi` issue was solved in the conda package, so right now it does not have to be an issue anymore, and if you don't have `certifi` installed, then #7850 will help... obviously, this is not working for previous versions, but 3.0 has the fix, it is solved there ;-)\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/94047442",
    "html_url": "https://github.com/ipython/ipython/issues/7829#issuecomment-94047442",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/7829",
    "id": 94047442,
    "node_id": "MDEyOklzc3VlQ29tbWVudDk0MDQ3NDQy",
    "user": {
      "login": "btabibian",
      "id": 730361,
      "node_id": "MDQ6VXNlcjczMDM2MQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/730361?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/btabibian",
      "html_url": "https://github.com/btabibian",
      "followers_url": "https://api.github.com/users/btabibian/followers",
      "following_url": "https://api.github.com/users/btabibian/following{/other_user}",
      "gists_url": "https://api.github.com/users/btabibian/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/btabibian/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/btabibian/subscriptions",
      "organizations_url": "https://api.github.com/users/btabibian/orgs",
      "repos_url": "https://api.github.com/users/btabibian/repos",
      "events_url": "https://api.github.com/users/btabibian/events{/privacy}",
      "received_events_url": "https://api.github.com/users/btabibian/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-04-17T18:35:23Z",
    "updated_at": "2015-04-17T18:35:59Z",
    "author_association": "NONE",
    "body": "For some reason I am having this problem again and only thing I get on JS console in chrome is following error:\n\nUncaught ReferenceError: Reveal is not defined\n\nI can open the presentation on Firefox but not on Chrome or Safari. \n\nI recently updated to IPython 3.1 and Chrome 42.0.2311.90 (64-bit)\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/94066116",
    "html_url": "https://github.com/ipython/ipython/issues/7829#issuecomment-94066116",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/7829",
    "id": 94066116,
    "node_id": "MDEyOklzc3VlQ29tbWVudDk0MDY2MTE2",
    "user": {
      "login": "damianavila",
      "id": 1640669,
      "node_id": "MDQ6VXNlcjE2NDA2Njk=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1640669?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/damianavila",
      "html_url": "https://github.com/damianavila",
      "followers_url": "https://api.github.com/users/damianavila/followers",
      "following_url": "https://api.github.com/users/damianavila/following{/other_user}",
      "gists_url": "https://api.github.com/users/damianavila/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/damianavila/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/damianavila/subscriptions",
      "organizations_url": "https://api.github.com/users/damianavila/orgs",
      "repos_url": "https://api.github.com/users/damianavila/repos",
      "events_url": "https://api.github.com/users/damianavila/events{/privacy}",
      "received_events_url": "https://api.github.com/users/damianavila/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-04-17T20:17:12Z",
    "updated_at": "2015-04-17T20:17:12Z",
    "author_association": "MEMBER",
    "body": "Can you tell me exactly what commands you used to make the slides? Can you also try cleaning your browser cache and reload it again? Thanks.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/94165541",
    "html_url": "https://github.com/ipython/ipython/issues/7829#issuecomment-94165541",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/7829",
    "id": 94165541,
    "node_id": "MDEyOklzc3VlQ29tbWVudDk0MTY1NTQx",
    "user": {
      "login": "btabibian",
      "id": 730361,
      "node_id": "MDQ6VXNlcjczMDM2MQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/730361?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/btabibian",
      "html_url": "https://github.com/btabibian",
      "followers_url": "https://api.github.com/users/btabibian/followers",
      "following_url": "https://api.github.com/users/btabibian/following{/other_user}",
      "gists_url": "https://api.github.com/users/btabibian/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/btabibian/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/btabibian/subscriptions",
      "organizations_url": "https://api.github.com/users/btabibian/orgs",
      "repos_url": "https://api.github.com/users/btabibian/repos",
      "events_url": "https://api.github.com/users/btabibian/events{/privacy}",
      "received_events_url": "https://api.github.com/users/btabibian/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-04-18T13:40:00Z",
    "updated_at": "2015-04-18T13:40:00Z",
    "author_association": "NONE",
    "body": "Thanks for the suggestion, cleaning the cache worked!! Any idea why this might happen? \n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/94166583",
    "html_url": "https://github.com/ipython/ipython/issues/7829#issuecomment-94166583",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/7829",
    "id": 94166583,
    "node_id": "MDEyOklzc3VlQ29tbWVudDk0MTY2NTgz",
    "user": {
      "login": "damianavila",
      "id": 1640669,
      "node_id": "MDQ6VXNlcjE2NDA2Njk=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1640669?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/damianavila",
      "html_url": "https://github.com/damianavila",
      "followers_url": "https://api.github.com/users/damianavila/followers",
      "following_url": "https://api.github.com/users/damianavila/following{/other_user}",
      "gists_url": "https://api.github.com/users/damianavila/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/damianavila/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/damianavila/subscriptions",
      "organizations_url": "https://api.github.com/users/damianavila/orgs",
      "repos_url": "https://api.github.com/users/damianavila/repos",
      "events_url": "https://api.github.com/users/damianavila/events{/privacy}",
      "received_events_url": "https://api.github.com/users/damianavila/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-04-18T13:58:00Z",
    "updated_at": "2015-04-18T13:58:06Z",
    "author_association": "MEMBER",
    "body": "The browsers are pretty aggressive caching js... so if you work with a previous version and it was cached you will have problem. I always use the browser in incognito mode and with the dev tools opened, then you can make a hard reload to be sure you are not hitting an old js...\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/94167504",
    "html_url": "https://github.com/ipython/ipython/issues/7829#issuecomment-94167504",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/7829",
    "id": 94167504,
    "node_id": "MDEyOklzc3VlQ29tbWVudDk0MTY3NTA0",
    "user": {
      "login": "btabibian",
      "id": 730361,
      "node_id": "MDQ6VXNlcjczMDM2MQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/730361?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/btabibian",
      "html_url": "https://github.com/btabibian",
      "followers_url": "https://api.github.com/users/btabibian/followers",
      "following_url": "https://api.github.com/users/btabibian/following{/other_user}",
      "gists_url": "https://api.github.com/users/btabibian/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/btabibian/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/btabibian/subscriptions",
      "organizations_url": "https://api.github.com/users/btabibian/orgs",
      "repos_url": "https://api.github.com/users/btabibian/repos",
      "events_url": "https://api.github.com/users/btabibian/events{/privacy}",
      "received_events_url": "https://api.github.com/users/btabibian/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-04-18T14:15:34Z",
    "updated_at": "2015-04-18T14:15:34Z",
    "author_association": "NONE",
    "body": "Thanks for your very helpful answer. I was on the verge of panicking :-)\n"
  }
]
