[
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/2538402",
    "html_url": "https://github.com/ipython/ipython/issues/934#issuecomment-2538402",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/934",
    "id": 2538402,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI1Mzg0MDI=",
    "user": {
      "login": "fperez",
      "id": 57394,
      "node_id": "MDQ6VXNlcjU3Mzk0",
      "avatar_url": "https://avatars1.githubusercontent.com/u/57394?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fperez",
      "html_url": "https://github.com/fperez",
      "followers_url": "https://api.github.com/users/fperez/followers",
      "following_url": "https://api.github.com/users/fperez/following{/other_user}",
      "gists_url": "https://api.github.com/users/fperez/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fperez/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fperez/subscriptions",
      "organizations_url": "https://api.github.com/users/fperez/orgs",
      "repos_url": "https://api.github.com/users/fperez/repos",
      "events_url": "https://api.github.com/users/fperez/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fperez/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2011-10-27T00:26:34Z",
    "updated_at": "2011-10-27T00:26:34Z",
    "author_association": "MEMBER",
    "body": "What version of Chrome and Tornado are you using?  Unfortunately, a few days ago in their dev channel, chrome changed their websocket protocol identifier and broke with released tornado.  Major PITA for us...\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/2538487",
    "html_url": "https://github.com/ipython/ipython/issues/934#issuecomment-2538487",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/934",
    "id": 2538487,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI1Mzg0ODc=",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2011-10-27T00:41:17Z",
    "updated_at": "2011-10-27T00:41:17Z",
    "author_association": "MEMBER",
    "body": "Yes, and tornado master has been updated to work.\n\nWe really need to draw a message on the error (426) that unsupported websockets causes.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/2538497",
    "html_url": "https://github.com/ipython/ipython/issues/934#issuecomment-2538497",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/934",
    "id": 2538497,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI1Mzg0OTc=",
    "user": {
      "login": "fperez",
      "id": 57394,
      "node_id": "MDQ6VXNlcjU3Mzk0",
      "avatar_url": "https://avatars1.githubusercontent.com/u/57394?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fperez",
      "html_url": "https://github.com/fperez",
      "followers_url": "https://api.github.com/users/fperez/followers",
      "following_url": "https://api.github.com/users/fperez/following{/other_user}",
      "gists_url": "https://api.github.com/users/fperez/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fperez/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fperez/subscriptions",
      "organizations_url": "https://api.github.com/users/fperez/orgs",
      "repos_url": "https://api.github.com/users/fperez/repos",
      "events_url": "https://api.github.com/users/fperez/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fperez/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2011-10-27T00:42:29Z",
    "updated_at": "2011-10-27T00:42:29Z",
    "author_association": "MEMBER",
    "body": "Marking for 0.12 so at least we provide a meaningful error instead of the blank stare of death :)\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/2539200",
    "html_url": "https://github.com/ipython/ipython/issues/934#issuecomment-2539200",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/934",
    "id": 2539200,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI1MzkyMDA=",
    "user": {
      "login": "certik",
      "id": 20568,
      "node_id": "MDQ6VXNlcjIwNTY4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/20568?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/certik",
      "html_url": "https://github.com/certik",
      "followers_url": "https://api.github.com/users/certik/followers",
      "following_url": "https://api.github.com/users/certik/following{/other_user}",
      "gists_url": "https://api.github.com/users/certik/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/certik/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/certik/subscriptions",
      "organizations_url": "https://api.github.com/users/certik/orgs",
      "repos_url": "https://api.github.com/users/certik/repos",
      "events_url": "https://api.github.com/users/certik/events{/privacy}",
      "received_events_url": "https://api.github.com/users/certik/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2011-10-27T03:03:35Z",
    "updated_at": "2011-10-27T03:03:41Z",
    "author_association": "NONE",
    "body": "I use the latest tornado, and Chrome 15.0.874.102. Definitely, some useful error message is necessary.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/2570850",
    "html_url": "https://github.com/ipython/ipython/issues/934#issuecomment-2570850",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/934",
    "id": 2570850,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI1NzA4NTA=",
    "user": {
      "login": "fperez",
      "id": 57394,
      "node_id": "MDQ6VXNlcjU3Mzk0",
      "avatar_url": "https://avatars1.githubusercontent.com/u/57394?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fperez",
      "html_url": "https://github.com/fperez",
      "followers_url": "https://api.github.com/users/fperez/followers",
      "following_url": "https://api.github.com/users/fperez/following{/other_user}",
      "gists_url": "https://api.github.com/users/fperez/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fperez/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fperez/subscriptions",
      "organizations_url": "https://api.github.com/users/fperez/orgs",
      "repos_url": "https://api.github.com/users/fperez/repos",
      "events_url": "https://api.github.com/users/fperez/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fperez/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2011-10-30T18:49:43Z",
    "updated_at": "2011-10-30T18:49:43Z",
    "author_association": "MEMBER",
    "body": "BTW, this is the [tornado commit](https://github.com/facebook/tornado/commit/84d7b458f956727c3b0d6710b68050186ce01a35) that fixed the problem for them.  I talked to Brian also about this, and I think the most sensible solution for our users is to apply that commit as a tornado monkeypatch for now.  I'm going to submit a PR with the monkeypatch just now so that our regular users don't have to fight too much with this for now.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/2570979",
    "html_url": "https://github.com/ipython/ipython/issues/934#issuecomment-2570979",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/934",
    "id": 2570979,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI1NzA5Nzk=",
    "user": {
      "login": "fperez",
      "id": 57394,
      "node_id": "MDQ6VXNlcjU3Mzk0",
      "avatar_url": "https://avatars1.githubusercontent.com/u/57394?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fperez",
      "html_url": "https://github.com/fperez",
      "followers_url": "https://api.github.com/users/fperez/followers",
      "following_url": "https://api.github.com/users/fperez/following{/other_user}",
      "gists_url": "https://api.github.com/users/fperez/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fperez/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fperez/subscriptions",
      "organizations_url": "https://api.github.com/users/fperez/orgs",
      "repos_url": "https://api.github.com/users/fperez/repos",
      "events_url": "https://api.github.com/users/fperez/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fperez/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2011-10-30T19:15:45Z",
    "updated_at": "2011-10-30T19:15:45Z",
    "author_association": "MEMBER",
    "body": "PR opened at #948 to take care of the tornado part. We'll close this once we also have a proper error message.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/2571965",
    "html_url": "https://github.com/ipython/ipython/issues/934#issuecomment-2571965",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/934",
    "id": 2571965,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI1NzE5NjU=",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2011-10-30T22:27:05Z",
    "updated_at": "2011-10-30T22:27:05Z",
    "author_association": "MEMBER",
    "body": "closed by merge of #948\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/2572383",
    "html_url": "https://github.com/ipython/ipython/issues/934#issuecomment-2572383",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/934",
    "id": 2572383,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI1NzIzODM=",
    "user": {
      "login": "certik",
      "id": 20568,
      "node_id": "MDQ6VXNlcjIwNTY4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/20568?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/certik",
      "html_url": "https://github.com/certik",
      "followers_url": "https://api.github.com/users/certik/followers",
      "following_url": "https://api.github.com/users/certik/following{/other_user}",
      "gists_url": "https://api.github.com/users/certik/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/certik/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/certik/subscriptions",
      "organizations_url": "https://api.github.com/users/certik/orgs",
      "repos_url": "https://api.github.com/users/certik/repos",
      "events_url": "https://api.github.com/users/certik/events{/privacy}",
      "received_events_url": "https://api.github.com/users/certik/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2011-10-30T23:43:05Z",
    "updated_at": "2011-10-30T23:43:05Z",
    "author_association": "NONE",
    "body": "I confirmed that this fixes it for me. I am closing the issue.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/2572430",
    "html_url": "https://github.com/ipython/ipython/issues/934#issuecomment-2572430",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/934",
    "id": 2572430,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI1NzI0MzA=",
    "user": {
      "login": "fperez",
      "id": 57394,
      "node_id": "MDQ6VXNlcjU3Mzk0",
      "avatar_url": "https://avatars1.githubusercontent.com/u/57394?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fperez",
      "html_url": "https://github.com/fperez",
      "followers_url": "https://api.github.com/users/fperez/followers",
      "following_url": "https://api.github.com/users/fperez/following{/other_user}",
      "gists_url": "https://api.github.com/users/fperez/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fperez/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fperez/subscriptions",
      "organizations_url": "https://api.github.com/users/fperez/orgs",
      "repos_url": "https://api.github.com/users/fperez/repos",
      "events_url": "https://api.github.com/users/fperez/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fperez/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2011-10-30T23:57:20Z",
    "updated_at": "2011-10-30T23:57:20Z",
    "author_association": "MEMBER",
    "body": "Nobody actually read my note above, did you ? :) \n\nI deliberately did _not_ close this issue until we also had a proper error message for the lack of websocket connections, though in all fairness that's a slightly different problem.  I was just trying to keep things simple by having only open open issue around the whole problem.\n\nOpened #952 then...\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/2572503",
    "html_url": "https://github.com/ipython/ipython/issues/934#issuecomment-2572503",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/934",
    "id": 2572503,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI1NzI1MDM=",
    "user": {
      "login": "certik",
      "id": 20568,
      "node_id": "MDQ6VXNlcjIwNTY4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/20568?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/certik",
      "html_url": "https://github.com/certik",
      "followers_url": "https://api.github.com/users/certik/followers",
      "following_url": "https://api.github.com/users/certik/following{/other_user}",
      "gists_url": "https://api.github.com/users/certik/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/certik/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/certik/subscriptions",
      "organizations_url": "https://api.github.com/users/certik/orgs",
      "repos_url": "https://api.github.com/users/certik/repos",
      "events_url": "https://api.github.com/users/certik/events{/privacy}",
      "received_events_url": "https://api.github.com/users/certik/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2011-10-31T00:16:06Z",
    "updated_at": "2011-10-31T00:16:06Z",
    "author_association": "NONE",
    "body": "I was thinking about this, but then concluded that this issue really is fixed, and the warning is a different issue (but I should have opened the new issue for it), and then hit \"comment & close\", and then I noticed, that Min has already closed it in the meantime.\n\nThanks for fixing it so fast! Everything works excellent for me again.\n"
  }
]
